# Generated by Django 5.2.8 on 2026-01-04 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_rename_blockplan_to_implementationplan'),
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortBlockPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('delivery_mode', models.CharField(choices=[('FULL_TIME', 'Full-Time (Contact)'), ('PART_TIME', 'Part-Time'), ('BLENDED', 'Blended Learning'), ('DISTANCE', 'Distance Learning')], max_length=20)),
                ('total_weeks', models.PositiveIntegerField()),
                ('contact_days_per_week', models.PositiveIntegerField(default=5)),
                ('hours_per_day', models.PositiveIntegerField(default=6)),
                ('classroom_hours_per_day', models.PositiveIntegerField(default=2)),
                ('practical_hours_per_day', models.PositiveIntegerField(default=4)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold')], default='DRAFT', max_length=20)),
                ('modification_log', models.JSONField(default=list, help_text='Log of modifications made to the plan')),
                ('cohort', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='block_plan', to='logistics.cohort')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('source_template', models.ForeignKey(blank=True, help_text='Original template this was copied from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohort_implementations', to='academics.implementationplan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cohort Block Plan',
                'verbose_name_plural': 'Cohort Block Plans',
            },
        ),
        migrations.CreateModel(
            name='CohortSchedulePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('phase_type', models.CharField(choices=[('INSTITUTIONAL', 'Institutional Training'), ('WORKPLACE_STINT', 'Workplace Stint')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('sequence', models.PositiveIntegerField()),
                ('duration_weeks', models.PositiveIntegerField()),
                ('year_level', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('planned_end', models.DateField(blank=True, null=True)),
                ('actual_start', models.DateField(blank=True, null=True)),
                ('actual_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('adjustment_reason', models.TextField(blank=True, help_text='Reason for schedule adjustment')),
                ('adjusted_at', models.DateTimeField(blank=True, null=True)),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjusted_phases', to=settings.AUTH_USER_MODEL)),
                ('cohort_block_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='logistics.cohortblockplan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('source_phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohort_implementations', to='academics.implementationphase')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cohort Schedule Phase',
                'verbose_name_plural': 'Cohort Schedule Phases',
                'ordering': ['cohort_block_plan', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='CohortModuleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sequence', models.PositiveIntegerField()),
                ('classroom_sessions', models.PositiveIntegerField(default=1)),
                ('practical_sessions', models.PositiveIntegerField(default=1)),
                ('total_days', models.PositiveIntegerField()),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('actual_days_used', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('completion_notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cohort_slots', to='academics.module')),
                ('source_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohort_implementations', to='academics.implementationmoduleslot')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('cohort_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_slots', to='logistics.cohortschedulephase')),
            ],
            options={
                'verbose_name': 'Cohort Module Slot',
                'verbose_name_plural': 'Cohort Module Slots',
                'ordering': ['cohort_phase', 'sequence'],
            },
        ),
    ]
