# Generated by Django Migration - Renames Cohort Block Plan to Cohort Implementation Plan
# This migration preserves all existing data

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Renames CohortBlockPlan, CohortSchedulePhase, and CohortModuleSlot 
    to CohortImplementationPlan, CohortImplementationPhase, and CohortImplementationModuleSlot.
    
    Data is preserved through Django's RenameModel and RenameField operations.
    """

    dependencies = [
        ('logistics', '0002_cohortblockplan_cohortschedulephase_cohortmoduleslot'),
        ('academics', '0008_rename_blockplan_to_implementationplan'),  # Must run after academics rename
    ]

    operations = [
        # Step 1: Rename CohortBlockPlan -> CohortImplementationPlan
        migrations.RenameModel(
            old_name='CohortBlockPlan',
            new_name='CohortImplementationPlan',
        ),
        
        # Step 2: Rename CohortSchedulePhase -> CohortImplementationPhase
        migrations.RenameModel(
            old_name='CohortSchedulePhase',
            new_name='CohortImplementationPhase',
        ),
        
        # Step 3: Rename CohortModuleSlot -> CohortImplementationModuleSlot
        migrations.RenameModel(
            old_name='CohortModuleSlot',
            new_name='CohortImplementationModuleSlot',
        ),
        
        # Step 4: Rename the related_name on Cohort FK from 'block_plan' -> 'implementation_plan'
        migrations.AlterField(
            model_name='cohortimplementationplan',
            name='cohort',
            field=models.OneToOneField(
                on_delete=models.CASCADE,
                related_name='implementation_plan',
                to='logistics.cohort',
            ),
        ),
        
        # Step 5: Rename source_template FK related_name from 'cohort_implementations' -> keep same
        # Also update the FK to point to renamed model (handled automatically by Django)
        migrations.AlterField(
            model_name='cohortimplementationplan',
            name='source_template',
            field=models.ForeignKey(
                blank=True,
                help_text='Original template this was copied from',
                null=True,
                on_delete=models.SET_NULL,
                related_name='cohort_implementations',
                to='academics.implementationplan',
            ),
        ),
        
        # Step 6: Rename cohort_block_plan FK field -> cohort_implementation_plan
        migrations.RenameField(
            model_name='cohortimplementationphase',
            old_name='cohort_block_plan',
            new_name='cohort_implementation_plan',
        ),
        
        # Step 7: Update source_phase FK to point to renamed model
        migrations.AlterField(
            model_name='cohortimplementationphase',
            name='source_phase',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name='cohort_implementations',
                to='academics.implementationphase',
            ),
        ),
        
        # Step 8: Rename cohort_phase FK field -> cohort_implementation_phase
        migrations.RenameField(
            model_name='cohortimplementationmoduleslot',
            old_name='cohort_phase',
            new_name='cohort_implementation_phase',
        ),
        
        # Step 9: Update source_slot FK to point to renamed model
        migrations.AlterField(
            model_name='cohortimplementationmoduleslot',
            name='source_slot',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name='cohort_implementations',
                to='academics.implementationmoduleslot',
            ),
        ),
    ]
