# Generated by Django 5.2.8 on 2026-01-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_rename_cohortblockplan_to_cohortimplementationplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cohortimplementationmoduleslot',
            options={'ordering': ['cohort_implementation_phase', 'sequence'], 'verbose_name': 'Cohort Implementation Module Slot', 'verbose_name_plural': 'Cohort Implementation Module Slots'},
        ),
        migrations.AlterModelOptions(
            name='cohortimplementationphase',
            options={'ordering': ['cohort_implementation_plan', 'sequence'], 'verbose_name': 'Cohort Implementation Phase', 'verbose_name_plural': 'Cohort Implementation Phases'},
        ),
        migrations.AlterModelOptions(
            name='cohortimplementationplan',
            options={'verbose_name': 'Cohort Implementation Plan', 'verbose_name_plural': 'Cohort Implementation Plans'},
        ),
        migrations.AlterField(
            model_name='cohortimplementationphase',
            name='phase_type',
            field=models.CharField(choices=[('INDUCTION', 'Induction'), ('INSTITUTIONAL', 'Institutional Training'), ('WORKPLACE_STINT', 'Workplace Stint'), ('INTEGRATION', 'Integration'), ('TRADE_TEST', 'Trade Test Preparation'), ('ASSESSMENT', 'Assessment')], max_length=20),
        ),
    ]
