# Generated by Django 5.2.8 on 2025-11-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppealRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('appeal_date', models.DateField()),
                ('grounds', models.TextField()),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('UPHELD', 'Upheld (Result Changed)'), ('DISMISSED', 'Dismissed'), ('WITHDRAWN', 'Withdrawn')], default='SUBMITTED', max_length=20)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True)),
                ('new_result', models.CharField(blank=True, max_length=5)),
            ],
            options={
                'verbose_name': 'Appeal Record',
                'verbose_name_plural': 'Appeal Records',
                'ordering': ['-appeal_date'],
            },
        ),
        migrations.CreateModel(
            name='AQP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('api_endpoint', models.URLField(blank=True)),
                ('api_key', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'AQP',
                'verbose_name_plural': 'AQPs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('activity_type', models.CharField(choices=[('TEST', 'Knowledge Test'), ('ASSIGNMENT', 'Assignment'), ('PRACTICAL', 'Practical Assessment'), ('LOGBOOK', 'Workplace Logbook'), ('PORTFOLIO', 'Portfolio Evidence'), ('SIMULATION', 'Simulation'), ('ORAL', 'Oral Assessment'), ('EXTERNAL', 'External Assessment')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('is_external', models.BooleanField(default=False)),
                ('sequence_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Assessment Activity',
                'verbose_name_plural': 'Assessment Activities',
                'ordering': ['module', 'sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('result', models.CharField(choices=[('C', 'Competent'), ('NYC', 'Not Yet Competent'), ('ABS', 'Absent'), ('DEF', 'Deferred')], max_length=5)),
                ('percentage_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('assessment_date', models.DateField()),
                ('feedback', models.TextField(blank=True)),
                ('evidence_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_MOD', 'Pending Moderation'), ('MODERATED', 'Moderated'), ('FINALIZED', 'Finalized'), ('APPEALED', 'Under Appeal')], default='DRAFT', max_length=20)),
                ('is_flagged_moderation', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('assessor_signature', models.TextField(blank=True)),
                ('assessor_signed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='ExternalAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('booking_date', models.DateField()),
                ('booking_reference', models.CharField(max_length=50)),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('assessment_venue', models.CharField(blank=True, max_length=200)),
                ('result', models.CharField(blank=True, choices=[('C', 'Competent'), ('NYC', 'Not Yet Competent')], max_length=5)),
                ('result_date', models.DateField(blank=True, null=True)),
                ('certificate_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CERTIFIED', 'Certified'), ('CANCELLED', 'Cancelled')], default='BOOKED', max_length=20)),
            ],
            options={
                'verbose_name': 'External Assessment',
                'verbose_name_plural': 'External Assessments',
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='ModerationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('original_result', models.CharField(max_length=5)),
                ('moderated_result', models.CharField(max_length=5)),
                ('is_upheld', models.BooleanField()),
                ('comments', models.TextField()),
                ('moderated_at', models.DateTimeField()),
                ('moderator_signature', models.TextField(blank=True)),
                ('moderator_signed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-moderated_at'],
            },
        ),
        migrations.CreateModel(
            name='PoEDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_reference', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'PoE Document',
                'verbose_name_plural': 'PoE Documents',
            },
        ),
        migrations.CreateModel(
            name='PoESubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('submission_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected - Resubmit'), ('PARTIAL', 'Partially Approved')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comments', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'PoE Submission',
                'verbose_name_plural': 'PoE Submissions',
                'ordering': ['-submission_date'],
            },
        ),
    ]
