# Generated by Django 5.2.8 on 2025-12-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentactivity",
            name="assessment_phase",
            field=models.CharField(
                choices=[("FORMATIVE", "Formative"), ("SUMMATIVE", "Summative")],
                default="FORMATIVE",
                help_text="Formative (internal) or Summative (external/final) assessment",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="assessmentactivity",
            name="is_eisa",
            field=models.BooleanField(
                default=False,
                help_text="External Integrated Summative Assessment - final QCTO exam",
                verbose_name="Is EISA",
            ),
        ),
    ]
