# Generated by Django 5.2.8 on 2026-02-17 07:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_year_based_progress'),
        ('logistics', '0004_alter_cohortimplementationmoduleslot_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_type', models.CharField(choices=[('PHOTO', 'Photo'), ('DOCUMENT', 'Document'), ('VIDEO', 'Video'), ('AUDIO', 'Audio')], default='PHOTO', max_length=20)),
                ('file', models.FileField(upload_to='assessments/evidence/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='assessments/evidence/thumbs/%Y/%m/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('offline_id', models.CharField(blank=True, help_text='Client-side ID for offline sync', max_length=100)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('assessment_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='assessments.assessmentresult')),
                ('captured_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='captured_evidence', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assessment Evidence',
                'verbose_name_plural': 'Assessment Evidence',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('is_auto_generated', models.BooleanField(default=True)),
                ('original_date', models.DateField(blank=True, null=True)),
                ('override_reason', models.TextField(blank=True)),
                ('overridden_at', models.DateTimeField(blank=True, null=True)),
                ('preparation_notes', models.TextField(blank=True, help_text='Notes for learners on how to prepare')),
                ('materials_required', models.TextField(blank=True, help_text='Materials learners should bring')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('POSTPONED', 'Postponed')], default='SCHEDULED', max_length=20)),
                ('learners_notified', models.BooleanField(default=False)),
                ('learners_notified_at', models.DateTimeField(blank=True, null=True)),
                ('parents_notified', models.BooleanField(default=False)),
                ('parents_notified_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='assessments.assessmentactivity')),
                ('assessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_schedules', to=settings.AUTH_USER_MODEL)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_schedules', to='logistics.cohort')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overridden_schedules', to=settings.AUTH_USER_MODEL)),
                ('source_session', models.ForeignKey(blank=True, help_text='ScheduleSession this was generated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_schedules', to='logistics.schedulesession')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_schedules', to='logistics.venue')),
            ],
            options={
                'verbose_name': 'Assessment Schedule',
                'verbose_name_plural': 'Assessment Schedules',
                'ordering': ['scheduled_date', 'scheduled_time'],
                'indexes': [models.Index(fields=['cohort', 'scheduled_date'], name='assessments_cohort__ba4380_idx'), models.Index(fields=['activity', 'status'], name='assessments_activit_a92386_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('CONFLICT', 'Conflict Resolved'), ('EVIDENCE', 'Evidence Uploaded')], max_length=20)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('client_timestamp', models.DateTimeField()),
                ('client_device_id', models.CharField(blank=True, max_length=100)),
                ('offline_id', models.CharField(blank=True, max_length=100)),
                ('server_timestamp', models.DateTimeField(blank=True, null=True)),
                ('had_conflict', models.BooleanField(default=False)),
                ('resolution', models.CharField(blank=True, choices=[('CLIENT_WINS', 'Client Timestamp Wins'), ('SERVER_WINS', 'Server Timestamp Wins'), ('MERGED', 'Merged Data'), ('MANUAL', 'Manual Resolution Required')], max_length=20)),
                ('resolution_details', models.JSONField(blank=True, null=True)),
                ('changes_applied', models.JSONField(default=dict)),
                ('facilitator_notified', models.BooleanField(default=False)),
                ('facilitator_notified_at', models.DateTimeField(blank=True, null=True)),
                ('assessment_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='assessments.assessmentresult')),
                ('synced_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assessment Sync Log',
                'verbose_name_plural': 'Assessment Sync Logs',
                'ordering': ['-synced_at'],
                'indexes': [models.Index(fields=['assessment_result', 'synced_at'], name='assessments_assessm_e2aa59_idx'), models.Index(fields=['had_conflict', 'facilitator_notified'], name='assessments_had_con_9f0130_idx')],
            },
        ),
    ]
