# Generated by Django 5.2.8 on 2025-12-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_task_hub_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_role',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
