# Generated by Django 5.2.8 on 2025-12-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_trainingnotification_notstakeholder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingnotification',
            name='funder',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('CORPORATE_DG', 'Corporate DG'), ('CORPORATE', 'Corporate'), ('MUNICIPALITY', 'Municipality'), ('GOVERNMENT', 'Government')], default='PRIVATE', max_length=30),
        ),
        migrations.AlterField(
            model_name='trainingnotification',
            name='project_type',
            field=models.CharField(choices=[('OC_APPRENTICESHIP', 'OC Apprenticeship'), ('OC_LEARNERSHIP', 'OC Learnership'), ('SKILLS_PROGRAMME', 'Skills Programme'), ('SHORT_COURSE', 'Short Course'), ('LEGACY_APPRENTICESHIP', 'Legacy Apprenticeship'), ('LEGACY_LEARNERSHIP', 'Legacy Learnership')], max_length=30),
        ),
    ]
