# Generated by Django 5.2.8 on 2025-12-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tranche_payment_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='NOTTaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_status', models.CharField(choices=[('DRAFT', 'Draft Created'), ('PLANNING', 'Planning Started'), ('IN_MEETING', 'In Planning Meeting'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('NOTIFICATIONS_SENT', 'Notifications Sent'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold')], help_text='NOT status that triggers this task', max_length=30)),
                ('project_type', models.CharField(blank=True, help_text='Optional: Only apply to specific project types (leave blank for all)', max_length=30)),
                ('funder_type', models.CharField(blank=True, help_text='Optional: Only apply to specific funder types (leave blank for all)', max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('task_title_template', models.CharField(help_text='Use {reference_number}, {title}, {qualification}, {learner_count}, {client_name}', max_length=200)),
                ('task_description_template', models.TextField(blank=True, help_text='Use same placeholders as title')),
                ('task_category', models.CharField(choices=[('doc_verify', 'Document Verification'), ('doc_upload', 'Document Upload Required'), ('assess_mark', 'Assessment to Mark'), ('assess_mod', 'Assessment to Moderate'), ('assess_due', 'Assessment Due'), ('poe_review', 'PoE to Review'), ('enroll_proc', 'Enrollment Processing'), ('reg_seta', 'SETA Registration'), ('inv_create', 'Invoice to Create'), ('pay_follow', 'Payment Follow-up'), ('pay_overdue', 'Overdue Payment'), ('attend_cap', 'Attendance to Capture'), ('log_update', 'Logbook to Update'), ('learn_risk', 'At-Risk Learner Intervention'), ('learn_support', 'Learner Support Required'), ('report_due', 'Report Due'), ('tranche', 'Tranche Claim Due'), ('follow_up', 'Follow-up Required'), ('callback', 'Callback Required'), ('approval', 'Approval Required'), ('review', 'Review Required'), ('action', 'Action Required'), ('reminder', 'Reminder')], default='action', max_length=20)),
                ('task_priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('assigned_role', models.CharField(choices=[('PROJECT_LEAD', 'Project Lead'), ('PROJECT_MANAGER', 'Project Manager'), ('FACILITATOR', 'Facilitator'), ('ASSESSOR', 'Assessor'), ('MODERATOR', 'Moderator'), ('RECRUITER', 'Recruiter'), ('FINANCE_LEAD', 'Finance Lead'), ('COMPLIANCE_LEAD', 'Compliance/SDF Lead'), ('LOGISTICS_LEAD', 'Logistics Coordinator'), ('QUALITY_LEAD', 'Quality Assurance Lead'), ('CLIENT_LIAISON', 'Client Liaison'), ('OBSERVER', 'Observer/Informed'), ('SUPPORT', 'Support Staff')], help_text='Role from NOTStakeholder to assign task to', max_length=30)),
                ('fallback_campus_role', models.CharField(blank=True, help_text="Fallback role from campus staff (e.g., 'REGISTRAR', 'ACADEMIC_COORDINATOR')", max_length=50)),
                ('due_days_offset', models.PositiveIntegerField(default=7, help_text='Days from status change when task is due')),
                ('sequence', models.PositiveIntegerField(default=1, help_text='Order of task creation for same trigger status')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'NOT Task Template',
                'verbose_name_plural': 'NOT Task Templates',
                'ordering': ['trigger_status', 'sequence'],
                'unique_together': {('trigger_status', 'name')},
            },
        ),
    ]
