# Generated by Django 5.2.8 on 2025-12-05 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_wbl_models'),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NOTIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('intake_number', models.PositiveIntegerField(default=1, help_text='Phase/class number within the project')),
                ('name', models.CharField(blank=True, help_text="e.g., 'Phase 1', 'Class A', 'Morning Group'", max_length=100)),
                ('original_cohort_size', models.PositiveIntegerField(default=0, help_text='Number of learners at project start (for dropout calculation)')),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('RECRUITING', 'Recruiting'), ('FILLED', 'Filled'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('intake_date', models.DateField(blank=True, help_text='Specific start date for this intake', null=True)),
                ('notes', models.TextField(blank=True)),
                ('cohort', models.ForeignKey(blank=True, help_text='Link to cohort for enrollment management', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='not_intakes', to='logistics.cohort')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('training_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='core.trainingnotification')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NOT Intake',
                'verbose_name_plural': 'NOT Intakes',
                'ordering': ['training_notification', 'intake_number'],
                'unique_together': {('training_notification', 'intake_number')},
            },
        ),
    ]
