# Generated by Django 5.2.8 on 2025-12-08 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_notintake"),
        ("tenants", "0002_extend_campus_code_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("password_hash", models.CharField(max_length=255)),
                ("employee_number", models.CharField(blank=True, max_length=50)),
                ("job_title", models.CharField(blank=True, max_length=100)),
                ("department", models.CharField(blank=True, max_length=100)),
                (
                    "access_justification",
                    models.TextField(
                        blank=True, help_text="Why the user needs the requested access"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Request expires if not reviewed by this date",
                        null=True,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_notes",
                    models.TextField(
                        blank=True, help_text="Admin notes about the decision"
                    ),
                ),
                ("verification_token", models.CharField(blank=True, max_length=100)),
                ("email_verified", models.BooleanField(default=False)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_access_requests",
                        to="tenants.brand",
                    ),
                ),
                (
                    "approved_campus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_access_requests",
                        to="tenants.campus",
                    ),
                ),
                (
                    "approved_roles",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The roles actually approved (admin can modify)",
                        related_name="approved_access_requests",
                        to="core.role",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_request_origin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_brand",
                    models.ForeignKey(
                        blank=True,
                        help_text="The brand/organization the user belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_requests",
                        to="tenants.brand",
                    ),
                ),
                (
                    "requested_campus",
                    models.ForeignKey(
                        blank=True,
                        help_text="The campus/site the user is based at",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_requests",
                        to="tenants.campus",
                    ),
                ),
                (
                    "requested_roles",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The roles/sections the user is requesting access to",
                        related_name="access_requests",
                        to="core.role",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_access_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Access Request",
                "verbose_name_plural": "Access Requests",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="AccessRequestSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon class or emoji", max_length=50
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "min_access_level",
                    models.CharField(
                        choices=[
                            ("SELF", "Self Service"),
                            ("CAMPUS", "Campus Level"),
                            ("BRAND", "Brand Level"),
                            ("HEAD_OFFICE", "Head Office"),
                        ],
                        default="CAMPUS",
                        help_text="Minimum organizational level to request this section",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "default_roles",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Roles granted when this section is approved",
                        related_name="access_sections",
                        to="core.role",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Access Request Section",
                "verbose_name_plural": "Access Request Sections",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="AccessRequestSectionChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "access_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_choices",
                        to="core.accessrequest",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_choices",
                        to="core.accessrequestsection",
                    ),
                ),
            ],
            options={
                "unique_together": {("access_request", "section")},
            },
        ),
    ]
