# Generated by Django 5.2.8 on 2025-12-08 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_access_request_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='notdeliverable',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Is this a recurring deliverable?'),
        ),
        migrations.AddField(
            model_name='notdeliverable',
            name='occurrence_number',
            field=models.PositiveIntegerField(blank=True, help_text='Which occurrence this is (1, 2, 3, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='notdeliverable',
            name='parent_deliverable',
            field=models.ForeignKey(blank=True, help_text='Parent deliverable if this is a recurring instance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_instances', to='core.notdeliverable'),
        ),
        migrations.AddField(
            model_name='notdeliverable',
            name='recurrence_end_date',
            field=models.DateField(blank=True, help_text='When to stop creating recurring deliverables', null=True),
        ),
        migrations.AddField(
            model_name='notdeliverable',
            name='recurrence_type',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('BIANNUALLY', 'Every 6 Months'), ('ANNUALLY', 'Annually')], help_text='How often the deliverable repeats', max_length=20),
        ),
    ]
