# Generated by Django 5.2.8 on 2025-12-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_add_recurring_deliverables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="code",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Super Administrator"),
                    ("SYSTEM_ADMIN", "System Administrator"),
                    ("HEAD_OFFICE_MANAGER", "Head Office Manager"),
                    ("FINANCE_DIRECTOR", "Finance Director"),
                    ("ACADEMIC_DIRECTOR", "Academic Director"),
                    ("CORPORATE_DIRECTOR", "Corporate Services Director"),
                    ("BRAND_MANAGER", "Brand Manager"),
                    ("BRAND_ACADEMIC_LEAD", "Brand Academic Lead"),
                    ("BRAND_FINANCE_LEAD", "Brand Finance Lead"),
                    ("CAMPUS_PRINCIPAL", "Campus Principal"),
                    ("CAMPUS_ADMIN", "Campus Administrator"),
                    ("REGISTRAR", "Registrar"),
                    ("ACADEMIC_COORDINATOR", "Academic Coordinator"),
                    ("FACILITATOR", "Facilitator"),
                    ("ASSESSOR", "Assessor"),
                    ("MODERATOR", "Moderator"),
                    ("QCTO_INTERNAL_MODERATOR", "QCTO Internal Moderator"),
                    ("SDF", "Skills Development Facilitator"),
                    ("SDF_ADMIN", "SDF Administrator"),
                    ("SALES_MANAGER", "Sales Manager"),
                    ("SALES_REP", "Sales Representative"),
                    ("FINANCE_MANAGER", "Finance Manager"),
                    ("FINANCE_CLERK", "Finance Clerk"),
                    ("LEARNER", "Learner"),
                    ("CORPORATE_CLIENT_ADMIN", "Corporate Client Administrator"),
                    ("CORPORATE_CLIENT_HR", "Corporate Client HR Manager"),
                    ("CORPORATE_CLIENT_SDF", "Corporate Client SDF"),
                    ("CORPORATE_EMPLOYEE", "Corporate Employee"),
                    ("WORKPLACE_OFFICER", "Workplace Officer"),
                    ("MENTOR", "Workplace Mentor"),
                    ("HOST_EMPLOYER_ADMIN", "Host Employer Administrator"),
                    ("LEAD_EMPLOYER_ADMIN", "Lead Employer Administrator"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
    ]
