# Generated by Django 5.2.8 on 2025-12-31 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_role_code"),
        ("tenants", "0002_extend_campus_code_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacilitatorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_number", models.CharField(blank=True, max_length=50)),
                (
                    "specializations",
                    models.TextField(
                        blank=True, help_text="Areas of expertise or specialization"
                    ),
                ),
                (
                    "campuses",
                    models.ManyToManyField(
                        blank=True,
                        help_text="All campuses where this facilitator can work",
                        related_name="facilitators",
                        to="tenants.campus",
                    ),
                ),
                (
                    "primary_campus",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary/default campus for reporting and filtering",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_facilitators",
                        to="tenants.campus",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User account for this facilitator",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilitator_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Facilitator Profile",
                "verbose_name_plural": "Facilitator Profiles",
            },
        ),
    ]
