# Generated by Django 5.2.8 on 2026-01-01 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_year_based_progress'),
        ('core', '0014_add_facilitator_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingnotification',
            name='has_stipend',
            field=models.BooleanField(default=False, help_text='Does this project include learner stipends?'),
        ),
        migrations.AddField(
            model_name='trainingnotification',
            name='stipend_daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default daily stipend rate for this project', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trainingnotification',
            name='stipend_escalation_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual escalation percentage for stipends', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='trainingnotification',
            name='stipend_frequency',
            field=models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='MONTHLY', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingnotification',
            name='stipend_notes',
            field=models.TextField(blank=True, help_text='Special conditions, payment terms, or escalation rules'),
        ),
        migrations.AddField(
            model_name='trainingnotification',
            name='stipend_start_month',
            field=models.PositiveIntegerField(blank=True, help_text='Month number when stipends start (1=first month, 2=second month, etc.)', null=True),
        ),
        migrations.CreateModel(
            name='NOTQualificationStipendRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('year_level', models.PositiveIntegerField(blank=True, help_text='Year/level of study (e.g., 1 for first year, 2 for second year)', null=True)),
                ('daily_rate', models.DecimalField(decimal_places=2, help_text='Daily stipend rate for this qualification/level', max_digits=10)),
                ('effective_from_month', models.PositiveIntegerField(default=1, help_text='Month number when this rate becomes effective (1=first month)')),
                ('effective_to_month', models.PositiveIntegerField(blank=True, help_text='Month number when this rate ends (leave blank for no end date)', null=True)),
                ('auto_escalate', models.BooleanField(default=False, help_text='Automatically escalate this rate annually')),
                ('escalation_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Annual escalation percentage if auto_escalate is enabled', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('qualification', models.ForeignKey(blank=True, help_text='Specific qualification (leave blank for default rate)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='not_stipend_rates', to='academics.qualification')),
                ('training_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification_stipend_rates', to='core.trainingnotification')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Qualification Stipend Rate',
                'verbose_name_plural': 'Qualification Stipend Rates',
                'ordering': ['training_notification', 'qualification', 'year_level', 'effective_from_month'],
                'unique_together': {('training_notification', 'qualification', 'year_level', 'effective_from_month')},
            },
        ),
    ]
