# Generated by Django 5.2.8 on 2026-01-08 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_not_stipend_configuration'),
        ('learners', '0011_workplaceexposurelog_workplacerotationrecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='NOTLearnerDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('REGISTRATION', 'Registration Documents'), ('CONFIRMATION', 'SETA/QCTO Confirmations'), ('AGREEMENT', 'Agreements & Contracts'), ('COMPLIANCE', 'Compliance Documents'), ('PROGRESS', 'Progress Reports'), ('CERTIFICATION', 'Certification Documents'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of this document type')),
                ('is_required', models.BooleanField(default=False, help_text='Is this document mandatory?')),
                ('required_for_project_types', models.JSONField(blank=True, default=list, help_text='List of project types this is required for (empty = all)')),
                ('required_for_funders', models.JSONField(blank=True, default=list, help_text='List of funder types this is required for (empty = all)')),
                ('has_expiry', models.BooleanField(default=False, help_text='Does this document type expire?')),
                ('default_validity_days', models.PositiveIntegerField(blank=True, help_text='Default validity period in days from issue date', null=True)),
                ('expiry_warning_days', models.PositiveIntegerField(default=30, help_text='Days before expiry to show warning/create task')),
                ('accepted_file_types', models.CharField(blank=True, default='.pdf,.doc,.docx,.jpg,.jpeg,.png', help_text='Comma-separated list of accepted file extensions', max_length=200)),
                ('max_file_size_mb', models.PositiveIntegerField(default=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Learner Document Type',
                'verbose_name_plural': 'Learner Document Types',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NOTProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document_type', models.CharField(choices=[('CONTRACT', 'Project Contract'), ('BULK_REGISTRATION', 'Bulk Registration Confirmation'), ('SETA_APPROVAL', 'SETA Approval Letter'), ('QCTO_APPROVAL', 'QCTO Approval'), ('FUNDING_AGREEMENT', 'Funding Agreement'), ('MOU', 'Memorandum of Understanding'), ('SLA', 'Service Level Agreement'), ('LEARNER_LIST', 'Approved Learner List'), ('PROGRESS_REPORT', 'Progress Report'), ('AUDIT_REPORT', 'Audit/Verification Report'), ('CERTIFICATE_BATCH', 'Batch Certificate List'), ('ATTENDANCE', 'Attendance Register'), ('FINANCIAL', 'Financial Document'), ('OTHER', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='not/project_documents/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_not_project_docs', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='core.notprojectdocument')),
                ('training_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_documents', to='core.trainingnotification')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Document',
                'verbose_name_plural': 'Project Documents',
                'ordering': ['training_notification', 'document_type', '-version'],
            },
        ),
        migrations.CreateModel(
            name='NOTLearnerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='not/learner_documents/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Upload'), ('UPLOADED', 'Uploaded - Awaiting Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reference_number', models.CharField(blank=True, help_text='Document reference number if applicable', max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('expiry_warning_sent', models.BooleanField(default=False)),
                ('expiry_warning_sent_at', models.DateTimeField(blank=True, null=True)),
                ('expiry_task_created', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='not_documents', to='learners.learner')),
                ('training_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_documents', to='core.trainingnotification')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_not_learner_docs', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='core.notlearnerdocumenttype')),
            ],
            options={
                'verbose_name': 'Learner Document',
                'verbose_name_plural': 'Learner Documents',
                'ordering': ['training_notification', 'learner', 'document_type'],
                'unique_together': {('training_notification', 'learner', 'document_type')},
            },
        ),
    ]
