# Generated by Django 5.2.8 on 2026-01-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_not_learner_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LOGBOOK_UNSIGNED', 'Logbook Requires Signature'), ('LOGBOOK_SIGNED', 'Logbook Signed'), ('ATTENDANCE_REMINDER', 'Attendance Submission Reminder'), ('ATTENDANCE_VERIFIED', 'Attendance Verified'), ('DISCIPLINARY_ACTION', 'Disciplinary Action'), ('DISCIPLINARY_REVIEW_DUE', 'Disciplinary Review Due'), ('STIPEND_CALCULATED', 'Stipend Calculated'), ('STIPEND_APPROVED', 'Stipend Approved'), ('PLACEMENT_VISIT_SCHEDULED', 'Placement Visit Scheduled'), ('PLACEMENT_STATUS_CHANGE', 'Placement Status Changed'), ('NEW_MESSAGE', 'New Message'), ('WM_COMPLETED', 'Workplace Module Completed'), ('WM_SIGNED', 'Workplace Module Signed Off'), ('TASK_COMPLETED', 'Service Task Completed'), ('TASK_EVIDENCE_UPLOADED', 'Task Evidence Uploaded'), ('SYSTEM', 'System Notification'), ('REMINDER', 'Reminder')], default='SYSTEM', max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_type',
            field=models.CharField(choices=[('LOGBOOK_UNSIGNED', 'Logbook Requires Signature'), ('LOGBOOK_SIGNED', 'Logbook Signed'), ('ATTENDANCE_REMINDER', 'Attendance Submission Reminder'), ('ATTENDANCE_VERIFIED', 'Attendance Verified'), ('DISCIPLINARY_ACTION', 'Disciplinary Action'), ('DISCIPLINARY_REVIEW_DUE', 'Disciplinary Review Due'), ('STIPEND_CALCULATED', 'Stipend Calculated'), ('STIPEND_APPROVED', 'Stipend Approved'), ('PLACEMENT_VISIT_SCHEDULED', 'Placement Visit Scheduled'), ('PLACEMENT_STATUS_CHANGE', 'Placement Status Changed'), ('NEW_MESSAGE', 'New Message'), ('WM_COMPLETED', 'Workplace Module Completed'), ('WM_SIGNED', 'Workplace Module Signed Off'), ('TASK_COMPLETED', 'Service Task Completed'), ('TASK_EVIDENCE_UPLOADED', 'Task Evidence Uploaded'), ('SYSTEM', 'System Notification'), ('REMINDER', 'Reminder')], max_length=30),
        ),
    ]
