# Generated by Django 5.2.8 on 2026-01-11 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_task_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitatorprofile',
            name='signature',
            field=models.ImageField(blank=True, help_text='Digital signature PNG (400x150px, transparent background)', null=True, upload_to='signatures/facilitators/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='facilitatorprofile',
            name='signature_captured_at',
            field=models.DateTimeField(blank=True, help_text='When signature was captured', null=True),
        ),
        migrations.AddField(
            model_name='facilitatorprofile',
            name='signature_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash for integrity verification', max_length=64),
        ),
        migrations.AddField(
            model_name='facilitatorprofile',
            name='signature_locked',
            field=models.BooleanField(default=False, help_text='Signature is locked after first capture'),
        ),
        migrations.AddField(
            model_name='workplaceofficerprofile',
            name='signature',
            field=models.ImageField(blank=True, help_text='Digital signature PNG (400x150px, transparent background)', null=True, upload_to='signatures/officers/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='workplaceofficerprofile',
            name='signature_captured_at',
            field=models.DateTimeField(blank=True, help_text='When signature was captured', null=True),
        ),
        migrations.AddField(
            model_name='workplaceofficerprofile',
            name='signature_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash for integrity verification', max_length=64),
        ),
        migrations.AddField(
            model_name='workplaceofficerprofile',
            name='signature_locked',
            field=models.BooleanField(default=False, help_text='Signature is locked after first capture'),
        ),
        migrations.CreateModel(
            name='SignatureCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('signature_image', models.ImageField(help_text='PNG image with transparent background (400x150px)', upload_to='signatures/%Y/%m/')),
                ('signature_hash', models.CharField(help_text='SHA-256 hash of the signature image for integrity verification', max_length=64)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which signature was captured', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Browser/device user agent string', max_length=500)),
                ('popia_consent_text', models.TextField(default='I consent to SkillsFlow storing and using my digital signature for the purpose of generating compliance documents, agreements, and certificates on my behalf. I understand that my signature will be securely stored in accordance with the Protection of Personal Information Act (POPIA) and will only be used for official training-related documentation. I confirm that I am the person whose signature is being captured and that this digital signature has the same legal effect as my handwritten signature.', help_text='Full consent text shown to user at time of capture')),
                ('popia_consent_given', models.BooleanField(default=True, help_text='User explicitly consented to signature storage')),
                ('popia_consent_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when consent was given')),
                ('is_locked', models.BooleanField(default=True, help_text='Locked signatures cannot be modified')),
                ('unlocked_at', models.DateTimeField(blank=True, help_text='When signature was unlocked', null=True)),
                ('unlock_reason', models.TextField(blank=True, help_text='Reason for unlocking (required for audit)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('unlocked_by', models.ForeignKey(blank=True, help_text='Admin who unlocked this signature', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures_unlocked', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='User this signature belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='signature_capture', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signature Capture',
                'verbose_name_plural': 'Signature Captures',
                'ordering': ['-captured_at'],
            },
        ),
    ]
