# Generated by Django 5.2.8 on 2026-01-11 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_digital_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique region code (e.g., GAU, WC, KZN)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Full region name (e.g., Gauteng, Western Cape)', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_modifier', models.DecimalField(decimal_places=4, default=1.0, help_text='Price modifier (1.0 = base price, 1.10 = +10%, 0.90 = -10%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent region for hierarchical grouping', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_regions', to='core.region')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
