# Generated by Django 5.2.8 on 2026-01-12 14:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_feature_improvements'),
        ('core', '0019_course_pricing_system'),
        ('learners', '0012_digital_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalModerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reference_number', models.CharField(editable=False, help_text='Auto-generated reference number', max_length=50, unique=True)),
                ('title', models.CharField(help_text='Brief description of moderation request', max_length=255)),
                ('etqa_name', models.CharField(help_text='Name of the ETQA body (e.g., NAMB, MerSETA, QCTO)', max_length=200)),
                ('etqa_contact_name', models.CharField(blank=True, help_text='Contact person at ETQA', max_length=200)),
                ('etqa_contact_email', models.EmailField(blank=True, help_text='ETQA contact email', max_length=254)),
                ('etqa_contact_phone', models.CharField(blank=True, help_text='ETQA contact phone', max_length=20)),
                ('sample_size', models.PositiveIntegerField(default=0, help_text='Number of learners in the moderation sample')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready to Submit'), ('SUBMITTED', 'Submitted to ETQA'), ('ACKNOWLEDGED', 'ETQA Acknowledged'), ('SCHEDULED', 'Visit Scheduled'), ('IN_PROGRESS', 'Moderation In Progress'), ('COMPLETED', 'Completed'), ('REQUIRES_RESUBMIT', 'Requires Resubmission'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('ready_date', models.DateField(blank=True, help_text='Date when learners are ready for moderation', null=True)),
                ('one_month_reminder_sent', models.BooleanField(default=False, help_text='Has the 1-month advance reminder been sent?')),
                ('submitted_date', models.DateField(blank=True, help_text='Date request was submitted to ETQA', null=True)),
                ('scheduled_date', models.DateField(blank=True, help_text='Scheduled date for the moderation visit', null=True)),
                ('completed_date', models.DateField(blank=True, help_text='Date moderation was completed', null=True)),
                ('request_document', models.FileField(blank=True, help_text='PDF or email attachment sent to ETQA', null=True, upload_to='moderation_requests/outgoing/%Y/%m/')),
                ('request_notes', models.TextField(blank=True, help_text='Notes or email content for the request')),
                ('response_document', models.FileField(blank=True, help_text='PDF or email response from ETQA', null=True, upload_to='moderation_requests/incoming/%Y/%m/')),
                ('response_notes', models.TextField(blank=True, help_text='ETQA response notes')),
                ('response_date', models.DateField(blank=True, help_text='Date of ETQA response', null=True)),
                ('result', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESSFUL', 'Successful'), ('PARTIAL', 'Partial Success (Corrections Required)'), ('UNSUCCESSFUL', 'Unsuccessful')], default='PENDING', max_length=20)),
                ('result_document', models.FileField(blank=True, help_text='Final moderation report/certificate from ETQA', null=True, upload_to='moderation_requests/results/%Y/%m/')),
                ('result_notes', models.TextField(blank=True, help_text='Summary of moderation result and any findings')),
                ('days_waiting', models.PositiveIntegerField(default=0, help_text='Days since submission (auto-calculated)')),
                ('escalation_notes', models.TextField(blank=True, help_text='Notes on escalation actions taken if ETQA is delayed')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Project admin responsible for this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_moderation_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('deliverable', models.ForeignKey(blank=True, help_text='The deliverable this moderation fulfills', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_requests', to='core.notdeliverable')),
                ('learners_for_moderation', models.ManyToManyField(blank=True, help_text='Learners selected for this moderation sample', related_name='moderation_requests', to='learners.learner')),
                ('training_notification', models.ForeignKey(help_text='The NOT project this moderation is for', on_delete=django.db.models.deletion.CASCADE, related_name='moderation_requests', to='core.trainingnotification')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'External Moderation Request',
                'verbose_name_plural': 'External Moderation Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text="e.g., 'Group 1', 'Group 2'", max_length=100)),
                ('group_number', models.PositiveIntegerField(default=1, help_text='Group number for ordering')),
                ('max_capacity', models.PositiveIntegerField(default=30, help_text='Maximum learners in this class')),
                ('schedule_notes', models.TextField(blank=True, help_text='Schedule information (days, times, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('facilitator', models.ForeignKey(blank=True, help_text='Facilitator responsible for this class', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_classes', to='core.facilitatorprofile')),
                ('intake', models.ForeignKey(blank=True, help_text='Optional link to specific intake within the NOT', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.notintake')),
                ('training_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_classes', to='core.trainingnotification')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training Class',
                'verbose_name_plural': 'Training Classes',
                'ordering': ['training_notification', 'group_number'],
                'unique_together': {('training_notification', 'group_number')},
            },
        ),
        migrations.CreateModel(
            name='LearnerClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_from', models.DateField(default=datetime.date.today, help_text='When learner was assigned to this class')),
                ('assigned_until', models.DateField(blank=True, help_text='When assignment ended (for class transfers)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('transfer_reason', models.TextField(blank=True, help_text='Reason for transfer if moved from another class')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='academics.enrollment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('previous_class', models.ForeignKey(blank=True, help_text='Previous class if this is a transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_from', to='core.trainingclass')),
                ('training_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_assignments', to='core.trainingclass')),
            ],
            options={
                'verbose_name': 'Learner Class Assignment',
                'verbose_name_plural': 'Learner Class Assignments',
                'ordering': ['-assigned_from'],
            },
        ),
    ]
