# Generated by Django 5.2.8 on 2026-01-12 20:04

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_feature_improvements'),
    ]

    operations = [
        migrations.CreateModel(
            name='NOTDeliverableEvidenceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deliverable_type', models.CharField(choices=[('REPORT', 'Report'), ('MILESTONE', 'Milestone'), ('REGISTRATION', 'Registration/Enrollment'), ('ASSESSMENT', 'Assessment Event'), ('MODERATION', 'Moderation'), ('CERTIFICATION', 'Certification'), ('AUDIT', 'Audit/Verification'), ('PAYMENT', 'Payment Milestone'), ('SUBMISSION', 'Document Submission'), ('MEETING', 'Progress Meeting'), ('OTHER', 'Other')], help_text='Which deliverable type this requirement applies to', max_length=50)),
                ('name', models.CharField(help_text='Name of required evidence', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Details of what is expected')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Must be provided for QC pass')),
                ('acceptance_criteria', models.TextField(blank=True, help_text='Criteria that must be met for this evidence to be accepted')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in checklist')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deliverable Evidence Requirement',
                'verbose_name_plural': 'Deliverable Evidence Requirements',
                'ordering': ['deliverable_type', 'order', 'name'],
                'unique_together': {('deliverable_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='NOTDeliverableEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(upload_to='deliverable_evidence/%Y/%m/', validators=[core.models.validate_evidence_file_extension, core.models.validate_evidence_file_size])),
                ('original_filename', models.CharField(help_text='Original uploaded filename', max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('NEEDS_REVISION', 'Needs Revision')], default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='core.notdeliverable')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliverable_evidence_verified', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(blank=True, help_text='Which QC requirement this evidence fulfills', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_evidence', to='core.notdeliverableevidencerequirement')),
            ],
            options={
                'verbose_name': 'Deliverable Evidence',
                'verbose_name_plural': 'Deliverable Evidence',
                'ordering': ['deliverable', '-created_at'],
            },
        ),
    ]
