# Generated by Django 5.2.8 on 2026-01-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_deliverable_evidence_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingnotification',
            name='auto_generate_invoices',
            field=models.BooleanField(default=True, help_text='Automatically generate invoices based on billing schedule'),
        ),
        migrations.AddField(
            model_name='trainingnotification',
            name='billing_schedule',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('DELIVERABLE', 'Based on Deliverables'), ('ANNUALLY', 'Annually'), ('UPFRONT', 'Upfront (Full Payment)'), ('MANUAL', 'Manual Override')], default='MONTHLY', help_text='How invoices will be generated for this project', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingnotification',
            name='funder',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('SETA', 'SETA'), ('CORPORATE_DG', 'Corporate DG'), ('CORPORATE', 'Corporate'), ('MUNICIPALITY', 'Municipality'), ('GOVERNMENT', 'Government')], default='PRIVATE', max_length=30),
        ),
        migrations.AlterField(
            model_name='tranchetemplate',
            name='funder_type',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('SETA', 'SETA'), ('CORPORATE_DG', 'Corporate DG'), ('CORPORATE', 'Corporate'), ('MUNICIPALITY', 'Municipality'), ('GOVERNMENT', 'Government')], max_length=30),
        ),
    ]
