# Generated by Django 5.2.8 on 2026-01-14 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_trainingnotification_auto_generate_invoices_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name for the template', max_length=100)),
                ('trigger_type', models.CharField(choices=[('status', 'Status Change'), ('date', 'Date Relative'), ('recurring', 'Recurring')], default='status', max_length=20)),
                ('trigger_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft Created'), ('PLANNING', 'Planning Started'), ('IN_MEETING', 'In Planning Meeting'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('NOTIFICATIONS_SENT', 'Notifications Sent'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold')], help_text='NOT status that triggers this task (for status-based triggers)', max_length=30)),
                ('date_reference', models.CharField(blank=True, choices=[('planned_start', 'Planned Start Date'), ('planned_end', 'Planned End Date'), ('actual_start', 'Actual Start Date'), ('actual_end', 'Actual End Date'), ('approval', 'Approval Date')], help_text='Reference date to calculate from (for date-relative triggers)', max_length=20)),
                ('offset_days', models.IntegerField(default=0, help_text='Days from reference date (negative = before, positive = after)')),
                ('recurring_interval', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], help_text='How often the task recurs', max_length=20)),
                ('recurring_start_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft Created'), ('PLANNING', 'Planning Started'), ('IN_MEETING', 'In Planning Meeting'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('NOTIFICATIONS_SENT', 'Notifications Sent'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold')], help_text='Start recurring when NOT reaches this status', max_length=30)),
                ('recurring_end_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft Created'), ('PLANNING', 'Planning Started'), ('IN_MEETING', 'In Planning Meeting'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('NOTIFICATIONS_SENT', 'Notifications Sent'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold')], help_text='Stop recurring when NOT reaches this status', max_length=30)),
                ('task_title_template', models.CharField(help_text='Use {reference_number}, {title}, {qualification}, {learner_count}, {client_name}, {due_date}', max_length=200)),
                ('task_description_template', models.TextField(blank=True, help_text='Use same placeholders as title')),
                ('task_category', models.CharField(choices=[('doc_verify', 'Document Verification'), ('doc_upload', 'Document Upload Required'), ('assess_mark', 'Assessment to Mark'), ('assess_mod', 'Assessment to Moderate'), ('assess_due', 'Assessment Due'), ('poe_review', 'PoE to Review'), ('enroll_proc', 'Enrollment Processing'), ('reg_seta', 'SETA Registration'), ('inv_create', 'Invoice to Create'), ('pay_follow', 'Payment Follow-up'), ('pay_overdue', 'Overdue Payment'), ('attend_cap', 'Attendance to Capture'), ('log_update', 'Logbook to Update'), ('learn_risk', 'At-Risk Learner Intervention'), ('learn_support', 'Learner Support Required'), ('report_due', 'Report Due'), ('tranche', 'Tranche Claim Due'), ('follow_up', 'Follow-up Required'), ('callback', 'Callback Required'), ('approval', 'Approval Required'), ('review', 'Review Required'), ('action', 'Action Required'), ('reminder', 'Reminder')], default='action', max_length=20)),
                ('task_priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('operational_category', models.CharField(blank=True, choices=[('admin', 'Administrative'), ('finance', 'Finance'), ('marketing', 'Marketing'), ('recruitment', 'Recruitment'), ('compliance', 'Compliance/Regulatory'), ('logistics', 'Logistics'), ('quality', 'Quality Assurance'), ('client', 'Client Relations'), ('hr', 'Human Resources'), ('reporting', 'Reporting')], help_text='Category for operational (non-academic) tasks', max_length=20)),
                ('assigned_role', models.CharField(choices=[('PROJECT_LEAD', 'Project Lead'), ('PROJECT_MANAGER', 'Project Manager'), ('FACILITATOR', 'Facilitator'), ('ASSESSOR', 'Assessor'), ('MODERATOR', 'Moderator'), ('RECRUITER', 'Recruiter'), ('FINANCE_LEAD', 'Finance Lead'), ('COMPLIANCE_LEAD', 'Compliance/SDF Lead'), ('LOGISTICS_LEAD', 'Logistics Coordinator'), ('QUALITY_LEAD', 'Quality Assurance Lead'), ('CLIENT_LIAISON', 'Client Liaison'), ('OBSERVER', 'Observer/Informed'), ('SUPPORT', 'Support Staff')], help_text='Role from NOTStakeholder to assign task to', max_length=30)),
                ('fallback_campus_role', models.CharField(blank=True, help_text="Fallback role from campus staff (e.g., 'REGISTRAR', 'ACADEMIC_COORDINATOR')", max_length=50)),
                ('due_days_offset', models.PositiveIntegerField(default=7, help_text='Days from trigger when task is due (for status-based triggers)')),
                ('recalculate_on_date_change', models.BooleanField(default=True, help_text='Recalculate task due dates when NOT dates change')),
                ('sequence', models.PositiveIntegerField(default=1, help_text='Order of task creation for same trigger')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Project Task Template',
                'verbose_name_plural': 'Project Task Templates',
                'ordering': ['template_set', 'trigger_type', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='NOTScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_due_date', models.DateField(blank=True, null=True)),
                ('trigger_date', models.DateField(blank=True, help_text='The date that triggered this task creation', null=True)),
                ('recurrence_number', models.PositiveIntegerField(default=1, help_text='Which occurrence this is (for recurring tasks)')),
                ('auto_generated', models.BooleanField(default=True)),
                ('recalculated_count', models.PositiveIntegerField(default=0)),
                ('last_recalculated', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_task_record', to='core.task')),
                ('training_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='core.trainingnotification')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tasks', to='core.projecttasktemplate')),
            ],
            options={
                'verbose_name': 'NOT Scheduled Task',
                'verbose_name_plural': 'NOT Scheduled Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTemplateSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('project_types', models.JSONField(blank=True, default=list, help_text='Project types this set applies to (empty = all). Use NOT PROJECT_TYPE_CHOICES values.')),
                ('funder_types', models.JSONField(blank=True, default=list, help_text='Funder types this set applies to (empty = all). Use NOT FUNDER_CHOICES values.')),
                ('qualification_types', models.JSONField(blank=True, default=list, help_text='Qualification types (OC, NC, ND, PQ, SP, LP) this set applies to (empty = all).')),
                ('min_duration_months', models.PositiveIntegerField(blank=True, help_text='Minimum contract duration (months) for this set to apply', null=True)),
                ('max_duration_months', models.PositiveIntegerField(blank=True, help_text='Maximum contract duration (months) for this set to apply', null=True)),
                ('auto_apply', models.BooleanField(default=True, help_text='Automatically apply this set when NOT matches criteria')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_template_sets', to=settings.AUTH_USER_MODEL)),
                ('parent_set', models.ForeignKey(blank=True, help_text='Inherit templates from a parent set', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_sets', to='core.projecttemplateset')),
            ],
            options={
                'verbose_name': 'Project Template Set',
                'verbose_name_plural': 'Project Template Sets',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='projecttasktemplate',
            name='template_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='core.projecttemplateset'),
        ),
        migrations.AlterUniqueTogether(
            name='projecttasktemplate',
            unique_together={('template_set', 'name')},
        ),
        migrations.CreateModel(
            name='NOTTemplateSetApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_version', models.PositiveIntegerField(help_text='Version of template set when applied')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('update_notification_sent', models.BooleanField(default=False)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_set_applications', to=settings.AUTH_USER_MODEL)),
                ('training_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_template_sets', to='core.trainingnotification')),
                ('template_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.projecttemplateset')),
            ],
            options={
                'verbose_name': 'NOT Template Set Application',
                'verbose_name_plural': 'NOT Template Set Applications',
                'unique_together': {('training_notification', 'template_set')},
            },
        ),
    ]
