# Generated by Django 5.2.8 on 2026-01-21 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_project_template_sets'),
        ('intakes', '0003_contract_and_learner_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingnotification',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='Link to parent contract (optional - for grouping multiple NOTs)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_notifications', to='intakes.contract'),
        ),
    ]
