# Generated by Django 5.2.8 on 2026-01-21 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_contract_and_learner_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingnotification',
            name='assessor',
            field=models.ForeignKey(blank=True, help_text='Primary assessor for this training project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='not_as_assessor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingnotification',
            name='facilitator',
            field=models.ForeignKey(blank=True, help_text='Primary facilitator for this training project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='not_as_facilitator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingnotification',
            name='moderator',
            field=models.ForeignKey(blank=True, help_text='Primary moderator for this training project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='not_as_moderator', to=settings.AUTH_USER_MODEL),
        ),
    ]
