# Generated by Django 5.2.8 on 2026-01-21 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_delivery_team_to_not'),
    ]

    operations = [
        migrations.AddField(
            model_name='notdeliverable',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Campus employee responsible for this deliverable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliverables', to=settings.AUTH_USER_MODEL),
        ),
    ]
