# Generated by Django 5.2.8 on 2026-02-06 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_assigned_to_deliverable'),
        ('logistics', '0004_alter_cohortimplementationmoduleslot_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceAllocationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('allocation_type', models.CharField(choices=[('FACILITATOR', 'Facilitator'), ('ASSESSOR', 'Assessor'), ('MODERATOR', 'Moderator'), ('VENUE', 'Venue')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_allocations', to='logistics.cohort')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('resource_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_periods', to='core.notresourcerequirement')),
                ('training_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_allocations', to='core.trainingnotification')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_allocations', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_allocations', to='logistics.venue')),
            ],
            options={
                'verbose_name': 'Resource Allocation Period',
                'verbose_name_plural': 'Resource Allocation Periods',
                'ordering': ['-start_date', 'allocation_type'],
                'indexes': [models.Index(fields=['user', 'start_date', 'end_date'], name='core_resour_user_id_7c8435_idx'), models.Index(fields=['venue', 'start_date', 'end_date'], name='core_resour_venue_i_f57411_idx'), models.Index(fields=['is_archived', 'end_date'], name='core_resour_is_arch_2bf4d9_idx')],
            },
        ),
    ]
