# Generated by Django 5.2.8 on 2026-02-16 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_add_resource_allocation_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTOTPDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(help_text='Base32-encoded TOTP secret', max_length=32)),
                ('is_confirmed', models.BooleanField(default=False, help_text='Whether the device has been verified by the user')),
                ('is_active', models.BooleanField(default=True, help_text='Whether 2FA is currently enabled for this user')),
                ('backup_codes', models.TextField(blank=True, help_text='Comma-separated backup codes for account recovery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totp_device', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User TOTP Device',
                'verbose_name_plural': 'User TOTP Devices',
            },
        ),
    ]
