# Generated by Django 5.2.8 on 2026-02-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_user_auth_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredDocumentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ID_COPY', 'ID Copy / Passport'), ('MATRIC', 'Matric Certificate'), ('PROOF_ADDRESS', 'Proof of Address'), ('QUALIFICATION', 'Prior Qualification'), ('CV', 'Curriculum Vitae'), ('BANK_CONFIRM', 'Bank Confirmation'), ('PROOF_OF_PAYMENT', 'Proof of Payment'), ('PARENT_ID', 'Parent/Guardian ID'), ('PARENT_CONSENT', 'Parent/Guardian Consent')], max_length=30, unique=True)),
                ('is_required', models.BooleanField(default=True, help_text='Whether this document is required for enrollment')),
                ('description', models.TextField(blank=True, help_text='Description shown to users')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Required Document Config',
                'verbose_name_plural': 'Required Document Configs',
                'ordering': ['order', 'document_type'],
            },
        ),
    ]
