# Generated by Django 5.2.8 on 2025-12-02 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tranche_payment_system'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tranche',
            field=models.ForeignKey(blank=True, help_text='Link invoice to a tranche for SETA funding claims', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.trancheschedule'),
        ),
    ]
