# Generated by Django 5.2.8 on 2025-12-08 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_add_tranche_to_invoice"),
        ("learners", "0003_guardian"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BursaryProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("NSFAS", "NSFAS"),
                            ("SETA", "SETA Bursary"),
                            ("CORPORATE", "Corporate Bursary"),
                            ("FOUNDATION", "Private Foundation"),
                            ("GOVERNMENT", "Government Grant"),
                            ("BANK", "Bank Student Loan"),
                            ("INTERNAL", "Internal Bursary"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("contact_person", models.CharField(blank=True, max_length=100)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                ("address", models.TextField(blank=True)),
                (
                    "requirements",
                    models.TextField(
                        blank=True,
                        help_text="Eligibility requirements for this bursary",
                    ),
                ),
                ("covers_tuition", models.BooleanField(default=True)),
                ("covers_registration", models.BooleanField(default=True)),
                ("covers_materials", models.BooleanField(default=False)),
                ("covers_accommodation", models.BooleanField(default=False)),
                ("covers_stipend", models.BooleanField(default=False)),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum amount per learner",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bursary Provider",
                "verbose_name_plural": "Bursary Providers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BursaryApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application_number",
                    models.CharField(blank=True, max_length=30, unique=True),
                ),
                ("application_date", models.DateField()),
                (
                    "external_reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference number from the provider",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("DOCUMENTS_REQUIRED", "Documents Required"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CONTRACT_PENDING", "Contract Pending"),
                            ("CONTRACT_SIGNED", "Contract Signed"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("status_changed_date", models.DateField(blank=True, null=True)),
                (
                    "amount_requested",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "amount_approved",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("covers_tuition", models.BooleanField(default=True)),
                ("covers_registration", models.BooleanField(default=False)),
                ("covers_materials", models.BooleanField(default=False)),
                ("covers_accommodation", models.BooleanField(default=False)),
                ("covers_stipend", models.BooleanField(default=False)),
                ("contract_signed", models.BooleanField(default=False)),
                ("contract_signed_date", models.DateField(blank=True, null=True)),
                (
                    "contract_file",
                    models.FileField(
                        blank=True, null=True, upload_to="bursary_contracts/"
                    ),
                ),
                ("contract_expiry", models.DateField(blank=True, null=True)),
                (
                    "repayment_required",
                    models.BooleanField(
                        default=False,
                        help_text="Does this bursary need to be repaid (e.g., if learner fails)?",
                    ),
                ),
                (
                    "service_obligation",
                    models.BooleanField(
                        default=False, help_text="Is there a work-back obligation?"
                    ),
                ),
                (
                    "obligation_terms",
                    models.TextField(
                        blank=True, help_text="Terms of repayment or service obligation"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bursary_applications",
                        to="learners.learner",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="finance.bursaryprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bursary Application",
                "verbose_name_plural": "Bursary Applications",
                "ordering": ["-application_date"],
            },
        ),
        migrations.CreateModel(
            name="DebitOrderMandate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "mandate_number",
                    models.CharField(blank=True, max_length=30, unique=True),
                ),
                ("account_holder_name", models.CharField(max_length=100)),
                (
                    "account_holder_id",
                    models.CharField(
                        blank=True,
                        help_text="ID number of account holder",
                        max_length=13,
                    ),
                ),
                (
                    "relationship_to_learner",
                    models.CharField(
                        blank=True,
                        help_text="Relationship of account holder to learner (e.g., Parent, Self)",
                        max_length=50,
                    ),
                ),
                ("bank_name", models.CharField(max_length=50)),
                ("branch_code", models.CharField(max_length=10)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("CHEQUE", "Cheque Account"),
                            ("SAVINGS", "Savings Account"),
                            ("TRANSMISSION", "Transmission Account"),
                        ],
                        max_length=20,
                    ),
                ),
                ("account_number", models.CharField(max_length=20)),
                (
                    "debit_day",
                    models.PositiveIntegerField(
                        help_text="Day of month for debit (1-28)"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly debit amount",
                        max_digits=10,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "signed_mandate_file",
                    models.FileField(
                        blank=True,
                        help_text="Signed mandate document",
                        null=True,
                        upload_to="debit_order_mandates/",
                    ),
                ),
                ("signed_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_SIGNATURE", "Pending Signature"),
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("last_debit_date", models.DateField(blank=True, null=True)),
                ("last_debit_status", models.CharField(blank=True, max_length=20)),
                ("failed_debit_count", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debit_order_mandates",
                        to="learners.learner",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Debit Order Mandate",
                "verbose_name_plural": "Debit Order Mandates",
                "ordering": ["-created_at"],
            },
        ),
    ]
