# Generated by Django 5.2.8 on 2025-12-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_bursaryprovider_bursaryapplication_debitordermandate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bursaryprovider",
            name="provider_type",
            field=models.CharField(
                choices=[
                    ("NSFAS", "NSFAS"),
                    ("SETA", "SETA Bursary"),
                    ("CORPORATE", "Corporate Bursary"),
                    ("FOUNDATION", "Private Foundation"),
                    ("GOVERNMENT", "Government Grant"),
                    ("BANK", "Bank Learner Loan"),
                    ("INTERNAL", "Internal Bursary"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
