# Generated by Django 5.2.8 on 2026-01-28 06:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_add_phase_type_choices'),
        ('finance', '0006_billingscheduletemplate_projectbillingschedule_and_more'),
        ('intakes', '0003_contract_and_learner_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='academic_year',
            field=models.PositiveIntegerField(blank=True, help_text='Specific academic year (e.g., 2026)', null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='enrollment_year',
            field=models.CharField(choices=[('CURRENT', 'Current Year'), ('NEXT', 'Next Year'), ('PLUS_TWO', 'Year After Next')], default='CURRENT', help_text='Academic year for enrollment', max_length=10),
        ),
        migrations.AddField(
            model_name='quote',
            name='intake',
            field=models.ForeignKey(blank=True, help_text='Intake this quote is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='intakes.intake'),
        ),
        migrations.AddField(
            model_name='quote',
            name='monthly_term',
            field=models.PositiveIntegerField(default=10, help_text='Number of monthly payments (for monthly plan)'),
        ),
        migrations.AddField(
            model_name='quote',
            name='payment_plan',
            field=models.CharField(choices=[('UPFRONT', 'Full Payment Upfront'), ('TWO_INSTALLMENTS', 'Two Installments'), ('MONTHLY', 'Monthly Payments')], default='UPFRONT', max_length=20),
        ),
        migrations.AddField(
            model_name='quote',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT rate (0% for individual learners, 15% for corporates)', max_digits=5),
        ),
        migrations.AddField(
            model_name='quote',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotelineitem',
            name='academic_year',
            field=models.PositiveIntegerField(blank=True, help_text='Academic year for this fee', null=True),
        ),
        migrations.AddField(
            model_name='quotelineitem',
            name='discount_reason',
            field=models.CharField(blank=True, help_text='Reason for discount if applicable', max_length=200),
        ),
        migrations.AddField(
            model_name='quotelineitem',
            name='item_type',
            field=models.CharField(choices=[('TUITION', 'Tuition Fee'), ('REGISTRATION', 'Registration Fee'), ('MATERIALS', 'Materials Fee'), ('ASSESSMENT', 'Assessment Fee'), ('OTHER', 'Other')], default='TUITION', max_length=20),
        ),
        migrations.AddField(
            model_name='quotelineitem',
            name='original_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price from price list/intake', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('VIEWED', 'Viewed'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CONVERTED', 'Converted to Invoice')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='terms',
            field=models.TextField(blank=True, default='This quote is valid for 48 hours from the date of issue.'),
        ),
        migrations.AlterField(
            model_name='quotelineitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Final quoted price (may differ from original)', max_digits=10),
        ),
        migrations.CreateModel(
            name='QualificationYearlyPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.PositiveIntegerField(help_text='Academic year (e.g., 2026)')),
                ('registration_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('materials_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_pricing', to='academics.qualification')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Qualification Yearly Pricing',
                'verbose_name_plural': 'Qualification Yearly Pricing',
                'ordering': ['-academic_year', 'qualification__short_title'],
                'unique_together': {('qualification', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='QuotePaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedule', to='finance.quote')),
            ],
            options={
                'verbose_name': 'Quote Payment Schedule',
                'verbose_name_plural': 'Quote Payment Schedules',
                'ordering': ['quote', 'installment_number'],
                'unique_together': {('quote', 'installment_number')},
            },
        ),
    ]
