# Generated by Django 5.2.8 on 2026-01-28 07:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_quote_enhancements'),
        ('tenants', '0002_extend_campus_code_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('installments', models.PositiveIntegerField(default=1, help_text='Number of installments (1 = full payment)')),
                ('deposit_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Deposit percentage of total (e.g., 10.00 = 10%)', max_digits=5)),
                ('monthly_term', models.PositiveIntegerField(default=10, help_text='Number of months for payment plan')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Option',
                'verbose_name_plural': 'Payment Options',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='payment_option',
            field=models.ForeignKey(blank=True, help_text='Payment option selected for this quote', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='finance.paymentoption'),
        ),
        migrations.CreateModel(
            name='QuoteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_terms', models.TextField(blank=True, help_text='Default terms and conditions')),
                ('header_text', models.TextField(blank=True, help_text='Header text appearing at top of quote')),
                ('footer_text', models.TextField(blank=True, help_text='Footer text appearing at bottom of quote')),
                ('validity_hours', models.PositiveIntegerField(default=48, help_text='How long quotes remain valid (in hours)')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('campus', models.ForeignKey(blank=True, help_text='If set, template only available for this campus', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_templates', to='tenants.campus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('parent_template', models.ForeignKey(blank=True, help_text='Parent template to inherit from (for campus overrides)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_templates', to='finance.quotetemplate')),
                ('payment_options', models.ManyToManyField(blank=True, help_text='Payment options available with this template', related_name='templates', to='finance.paymentoption')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quote Template',
                'verbose_name_plural': 'Quote Templates',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template used to create this quote', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='finance.quotetemplate'),
        ),
    ]
