# Generated by Django 5.2.8 on 2025-12-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
