# Generated by Django 5.2.8 on 2026-02-11 05:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0030_alter_integrationconnection_api_key_and_more'),
        ('tenants', '0002_extend_campus_code_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandSocialAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('META', 'Meta (Facebook + Instagram)'), ('TIKTOK', 'TikTok'), ('GOOGLE_ANALYTICS', 'Google Analytics 4')], max_length=20)),
                ('facebook_page_id', models.CharField(blank=True, help_text='Facebook Page ID', max_length=50)),
                ('facebook_page_name', models.CharField(blank=True, max_length=200)),
                ('facebook_page_access_token', models.TextField(blank=True, help_text='Long-lived Page Access Token')),
                ('instagram_business_id', models.CharField(blank=True, help_text='Instagram Business Account ID', max_length=50)),
                ('instagram_username', models.CharField(blank=True, max_length=100)),
                ('tiktok_business_id', models.CharField(blank=True, help_text='TikTok Business Center ID', max_length=50)),
                ('tiktok_advertiser_id', models.CharField(blank=True, help_text='TikTok Advertiser ID', max_length=50)),
                ('tiktok_username', models.CharField(blank=True, max_length=100)),
                ('ga4_property_id', models.CharField(blank=True, help_text='GA4 Property ID (e.g., 123456789)', max_length=50)),
                ('ga4_property_name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(blank=True, max_length=50)),
                ('sync_error', models.TextField(blank=True)),
                ('has_analytics_permission', models.BooleanField(default=False, help_text='Has permission to read analytics/insights')),
                ('has_messaging_permission', models.BooleanField(default=False, help_text='Has permission to send/receive messages')),
                ('messaging_approval_status', models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_REQUIRED', help_text='Meta App Review status for messaging', max_length=20)),
                ('backfill_complete', models.BooleanField(default=False)),
                ('backfill_start_date', models.DateField(blank=True, help_text='Earliest date with data', null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='tenants.brand')),
                ('connection', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_account', to='integrations.integrationconnection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Brand Social Account',
                'verbose_name_plural': 'Brand Social Accounts',
                'ordering': ['brand__name', 'platform'],
                'unique_together': {('brand', 'platform')},
            },
        ),
    ]
