# Generated by Django 5.2.8 on 2026-02-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_brandsocialaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='max_learner_capacity',
            field=models.PositiveIntegerField(default=300, help_text='Maximum total learners this campus can handle (including off-site learners)'),
        ),
        migrations.AddField(
            model_name='campus',
            name='on_campus_capacity',
            field=models.PositiveIntegerField(default=150, help_text='Maximum learners that can be on-campus at any time (physical seats)'),
        ),
        migrations.AddField(
            model_name='campus',
            name='target_utilization',
            field=models.PositiveIntegerField(default=85, help_text='Target utilization percentage (e.g., 85 = 85%)'),
        ),
    ]
