# Generated by Django 5.2.8 on 2026-01-11 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('entity_type', models.CharField(choices=[('enrollment', 'Enrollment'), ('learner', 'Learner'), ('corporate_client', 'Corporate Client'), ('training_notification', 'Training Notification'), ('invoice', 'Invoice'), ('assessment', 'Assessment'), ('poe_submission', 'PoE Submission'), ('grant_project', 'Grant Project')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Process Flow',
                'verbose_name_plural': 'Process Flows',
                'ordering': ['entity_type'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(help_text='Internal code matching model status field', max_length=30)),
                ('name', models.CharField(help_text='Display name', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('stage_type', models.CharField(choices=[('initial', 'Initial Stage'), ('intermediate', 'Intermediate Stage'), ('terminal_success', 'Terminal (Success)'), ('terminal_failure', 'Terminal (Failure)')], default='intermediate', max_length=20)),
                ('sequence_order', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='gray', help_text='Tailwind color class', max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Icon name', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_reason_on_entry', models.BooleanField(default=False, help_text='Require reason when entering this stage')),
                ('auto_tasks', models.JSONField(blank=True, default=list, help_text='Tasks to auto-create when entering stage')),
                ('notifications', models.JSONField(blank=True, default=list, help_text='Notifications to send when entering stage')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('process_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='workflows.processflow')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Process Stage',
                'verbose_name_plural': 'Process Stages',
                'ordering': ['process_flow', 'sequence_order'],
                'unique_together': {('process_flow', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ProcessStageTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_allowed', models.BooleanField(default=True)),
                ('requires_reason', models.BooleanField(default=False, help_text='Require reason for this transition')),
                ('requires_approval', models.BooleanField(default=False, help_text='Requires approval from supervisor')),
                ('approval_role', models.CharField(blank=True, help_text='Role required for approval', max_length=50)),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text="Custom validation rules, e.g., {'required_fields': ['certificate_number']}")),
                ('auto_transition', models.BooleanField(default=False, help_text='Automatically transition when conditions met')),
                ('auto_transition_conditions', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('from_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='workflows.processstage')),
                ('process_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='workflows.processflow')),
                ('to_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='workflows.processstage')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stage Transition',
                'verbose_name_plural': 'Stage Transitions',
                'unique_together': {('process_flow', 'from_stage', 'to_stage')},
            },
        ),
        migrations.CreateModel(
            name='TransitionAttemptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.PositiveIntegerField()),
                ('from_stage', models.CharField(max_length=30)),
                ('to_stage', models.CharField(max_length=30)),
                ('was_allowed', models.BooleanField()),
                ('was_blocked', models.BooleanField(default=False)),
                ('block_reason', models.TextField(blank=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('reason_provided', models.TextField(blank=True)),
                ('attempted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transition_attempts', to=settings.AUTH_USER_MODEL)),
                ('process_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_logs', to='workflows.processflow')),
            ],
            options={
                'verbose_name': 'Transition Attempt Log',
                'verbose_name_plural': 'Transition Attempt Logs',
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='workflows_t_entity__c7590f_idx'), models.Index(fields=['was_blocked', 'attempted_at'], name='workflows_t_was_blo_458f1c_idx')],
            },
        ),
    ]
