# Generated by Django 5.2.8 on 2026-01-14 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_sop_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sop',
            options={'ordering': ['category', 'name'], 'verbose_name': 'SOP', 'verbose_name_plural': 'SOPs'},
        ),
        migrations.AlterField(
            model_name='sop',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sop',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sop',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sop',
            name='estimated_duration',
            field=models.CharField(blank=True, help_text="e.g., '15 minutes', '1 hour'", max_length=50),
        ),
        migrations.AlterField(
            model_name='sop',
            name='owner',
            field=models.CharField(blank=True, help_text='Department or role responsible for maintaining this SOP', max_length=100),
        ),
        migrations.AlterField(
            model_name='sop',
            name='purpose',
            field=models.TextField(blank=True, help_text='Why this SOP exists and when to use it'),
        ),
        migrations.AlterField(
            model_name='sop',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sopcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sopcategory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sopcategory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sopstep',
            name='app_url_label',
            field=models.CharField(blank=True, help_text="Button text, e.g., 'Go to Enrollments'", max_length=100),
        ),
        migrations.AlterField(
            model_name='sopstep',
            name='app_url_name',
            field=models.CharField(blank=True, help_text="Django URL name to link to, e.g., 'core:enrollment_list'", max_length=200),
        ),
        migrations.AlterField(
            model_name='sopstep',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sopstep',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sopstep',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed instructions for this step'),
        ),
        migrations.AlterField(
            model_name='sopstep',
            name='external_url',
            field=models.URLField(blank=True, help_text='External link if not an app location'),
        ),
        migrations.AlterField(
            model_name='sopstep',
            name='responsible_role',
            field=models.CharField(blank=True, help_text="e.g., 'Admin', 'Finance'", max_length=100),
        ),
        migrations.AlterField(
            model_name='sopstep',
            name='tips',
            field=models.TextField(blank=True, help_text='Pro tips or common mistakes to avoid'),
        ),
        migrations.AlterField(
            model_name='sopstep',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
