# Generated by Django 5.2.8 on 2025-12-03 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0005_add_user_to_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateclient',
            name='is_host_employer',
            field=models.BooleanField(default=False, help_text='This client can host learners for workplace-based learning'),
        ),
        migrations.AddField(
            model_name='corporateclient',
            name='is_lead_employer',
            field=models.BooleanField(default=False, help_text='This client is a lead employer overseeing placements at host employers'),
        ),
        migrations.AddField(
            model_name='corporatecontact',
            name='can_approve_logbooks',
            field=models.BooleanField(default=False, help_text='Can sign off on learner logbooks'),
        ),
        migrations.AddField(
            model_name='corporatecontact',
            name='can_submit_attendance',
            field=models.BooleanField(default=False, help_text='Can submit attendance on behalf of the organisation'),
        ),
        migrations.AddField(
            model_name='corporatecontact',
            name='can_view_placements',
            field=models.BooleanField(default=False, help_text='Can view placement details and reports'),
        ),
        migrations.AddField(
            model_name='corporatecontact',
            name='is_mentor',
            field=models.BooleanField(default=False, help_text='This contact can act as a mentor for learners'),
        ),
        migrations.AddField(
            model_name='hostmentor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workplaceplacement',
            name='lead_employer',
            field=models.ForeignKey(blank=True, help_text='Lead employer if different from host employer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_employer_placements', to='corporate.corporateclient'),
        ),
        migrations.AddField(
            model_name='workplaceplacement',
            name='stipend_daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Daily stipend rate for this placement', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workplaceplacement',
            name='stipend_payment_day',
            field=models.PositiveIntegerField(default=25, help_text='Day of month stipend is paid'),
        ),
        migrations.AddField(
            model_name='workplaceplacement',
            name='workplace_officer',
            field=models.ForeignKey(blank=True, help_text='Assigned workplace monitoring officer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_placements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('annual_leave_days_per_year', models.PositiveIntegerField(default=15, help_text='Total annual leave days per year (pro-rated for placement duration)')),
                ('annual_leave_paid', models.BooleanField(default=True, help_text='Whether annual leave is paid')),
                ('sick_leave_days_per_month', models.PositiveIntegerField(default=2, help_text='Paid sick leave days allowed per month')),
                ('sick_leave_requires_documentation_after_days', models.PositiveIntegerField(default=2, help_text='Sick note required after this many consecutive days')),
                ('family_responsibility_days_per_year', models.PositiveIntegerField(default=3, help_text='Total family responsibility leave days per year')),
                ('family_leave_paid', models.BooleanField(default=True, help_text='Whether family responsibility leave is paid')),
                ('public_holidays_paid', models.BooleanField(default=True, help_text='Whether public holidays are paid')),
                ('standard_hours_per_day', models.DecimalField(decimal_places=2, default=8, help_text='Standard working hours per day', max_digits=4)),
                ('is_default', models.BooleanField(default=False, help_text='Use as default policy for new placements')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Policy',
                'verbose_name_plural': 'Leave Policies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='workplaceplacement',
            name='leave_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements', to='corporate.leavepolicy'),
        ),
    ]
