# Generated by Django 5.2.8 on 2025-12-08 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_year_based_progress"),
        ("corporate", "0007_wspatr_enhanced"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkplaceStint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "stint_number",
                    models.PositiveIntegerField(
                        choices=[(1, "Stint 1"), (2, "Stint 2"), (3, "Stint 3")],
                        help_text="Stint sequence (1, 2, or 3)",
                    ),
                ),
                (
                    "year_level",
                    models.PositiveIntegerField(
                        choices=[(1, "Year 1"), (2, "Year 2"), (3, "Year 3")],
                        help_text="Which program year this stint occurs in",
                    ),
                ),
                (
                    "duration_days_required",
                    models.PositiveIntegerField(
                        help_text="Minimum number of workplace days required for this stint"
                    ),
                ),
                (
                    "duration_weeks",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Approximate weeks (calculated from days / 5)",
                        null=True,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Learning objectives and expectations for this stint",
                    ),
                ),
                ("sequence_order", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modules",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Workplace modules to be completed during this stint",
                        limit_choices_to={"module_type": "W"},
                        related_name="workplace_stints",
                        to="academics.module",
                    ),
                ),
                (
                    "qualification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workplace_stints",
                        to="academics.qualification",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Workplace Stint",
                "verbose_name_plural": "Workplace Stints",
                "ordering": ["qualification", "stint_number"],
                "unique_together": {("qualification", "stint_number")},
            },
        ),
        migrations.AddField(
            model_name="workplaceplacement",
            name="workplace_stint",
            field=models.ForeignKey(
                blank=True,
                help_text="Which stint requirement this placement fulfills",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="placements",
                to="corporate.workplacestint",
            ),
        ),
    ]
