# Generated by Django 5.2.8 on 2025-12-08 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0009_rename_trade_test_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legacytradetestappeal',
            options={'ordering': ['-appeal_date'], 'verbose_name': 'Legacy Trade Test Appeal', 'verbose_name_plural': 'Legacy Trade Test Appeals'},
        ),
        migrations.AlterModelOptions(
            name='legacytradetestbooking',
            options={'ordering': ['-scheduled_date'], 'verbose_name': 'Legacy Trade Test Booking', 'verbose_name_plural': 'Legacy Trade Test Bookings'},
        ),
        migrations.AlterModelOptions(
            name='legacytradetestresult',
            options={'ordering': ['-test_date'], 'verbose_name': 'Legacy Trade Test Result', 'verbose_name_plural': 'Legacy Trade Test Results'},
        ),
    ]
