# Generated by Django 5.2.8 on 2025-12-19 05:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_year_based_progress"),
        ("corporate", "0010_alter_legacytradetestappeal_options_and_more"),
        ("learners", "0003_guardian"),
        ("tenants", "0002_extend_campus_code_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "quarter",
                    models.CharField(
                        choices=[
                            ("Q1", "Q1 (Jan-Mar)"),
                            ("Q2", "Q2 (Apr-Jun)"),
                            ("Q3", "Q3 (Jul-Sep)"),
                            ("Q4", "Q4 (Oct-Dec)"),
                        ],
                        max_length=2,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "default_agenda",
                    models.JSONField(
                        default=list,
                        help_text='List of agenda items: [{"title": "...", "description": "...", "duration_minutes": 15}]',
                    ),
                ),
                (
                    "suggested_month",
                    models.PositiveIntegerField(
                        help_text="Suggested month (1-12) for this meeting",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                ("preparation_notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Meeting Template",
                "verbose_name_plural": "Meeting Templates",
                "ordering": ["quarter", "name"],
            },
        ),
        migrations.CreateModel(
            name="SETAExportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "export_type",
                    models.CharField(
                        choices=[
                            ("WSP", "WSP Submission"),
                            ("ATR", "ATR Submission"),
                            ("EMPLOYEE_DATA", "Employee Data"),
                            ("TRAINING_DATA", "Training Data"),
                            ("PIVOTAL", "PIVOTAL Data"),
                            ("COMMITTEE_ATTENDANCE", "Committee Attendance"),
                            ("COMBINED", "Combined WSP/ATR"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "column_mappings",
                    models.JSONField(
                        default=list, help_text="Column mapping configuration"
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        choices=[
                            ("XLSX", "Excel (.xlsx)"),
                            ("CSV", "CSV (.csv)"),
                            ("XML", "XML"),
                        ],
                        default="XLSX",
                        max_length=10,
                    ),
                ),
                (
                    "template_file",
                    models.FileField(
                        blank=True,
                        help_text="SETA-provided template file",
                        null=True,
                        upload_to="seta_templates/",
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("superseded_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "seta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corporate_export_templates",
                        to="learners.seta",
                    ),
                ),
            ],
            options={
                "verbose_name": "SETA Export Template",
                "verbose_name_plural": "SETA Export Templates",
                "ordering": ["seta__name", "export_type", "-version"],
            },
        ),
        migrations.CreateModel(
            name="TrainingCommittee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(default="Training Committee", max_length=200),
                ),
                (
                    "constitution_date",
                    models.DateField(
                        blank=True,
                        help_text="Date committee was constituted",
                        null=True,
                    ),
                ),
                (
                    "constitution_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="training_committees/constitutions/",
                    ),
                ),
                (
                    "meeting_frequency",
                    models.CharField(
                        choices=[
                            ("QUARTERLY", "Quarterly (4 per year)"),
                            ("BI_MONTHLY", "Bi-Monthly (6 per year)"),
                            ("MONTHLY", "Monthly (12 per year)"),
                        ],
                        default="QUARTERLY",
                        max_length=20,
                    ),
                ),
                ("send_calendar_invites", models.BooleanField(default=True)),
                ("include_zoom_link", models.BooleanField(default=False)),
                (
                    "default_meeting_duration_minutes",
                    models.PositiveIntegerField(default=120),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_items",
                        to="tenants.campus",
                    ),
                ),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_committee",
                        to="corporate.corporateclient",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Training Committee",
                "verbose_name_plural": "Training Committees",
            },
        ),
        migrations.CreateModel(
            name="TrainingCommitteeMeeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "meeting_number",
                    models.PositiveIntegerField(
                        default=1, help_text="Meeting number in sequence"
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("scheduled_time", models.TimeField()),
                ("duration_minutes", models.PositiveIntegerField(default=120)),
                (
                    "meeting_type",
                    models.CharField(
                        choices=[
                            ("IN_PERSON", "In Person"),
                            ("VIRTUAL", "Virtual"),
                            ("HYBRID", "Hybrid"),
                        ],
                        default="VIRTUAL",
                        max_length=15,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Physical location or virtual platform",
                        max_length=200,
                    ),
                ),
                (
                    "meeting_link",
                    models.URLField(
                        blank=True, help_text="Zoom/Teams/Google Meet link"
                    ),
                ),
                (
                    "meeting_id",
                    models.CharField(
                        blank=True,
                        help_text="External meeting ID (e.g., Zoom meeting ID)",
                        max_length=100,
                    ),
                ),
                ("meeting_password", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SCHEDULED", "Scheduled"),
                            ("INVITES_SENT", "Invites Sent"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("POSTPONED", "Postponed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("invites_sent_date", models.DateTimeField(blank=True, null=True)),
                ("reminder_sent_date", models.DateTimeField(blank=True, null=True)),
                ("actual_start_time", models.TimeField(blank=True, null=True)),
                ("actual_end_time", models.TimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_items",
                        to="tenants.campus",
                    ),
                ),
                (
                    "committee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="corporate.trainingcommittee",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organized_tc_meetings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meetings",
                        to="corporate.meetingtemplate",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Training Committee Meeting",
                "verbose_name_plural": "Training Committee Meetings",
                "ordering": ["-scheduled_date", "-scheduled_time"],
            },
        ),
        migrations.CreateModel(
            name="TrainingCommitteeMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("CHAIRPERSON", "Chairperson"),
                            ("SECRETARY", "Secretary"),
                            ("SDF", "Skills Development Facilitator"),
                            ("EMPLOYER_REP", "Employer Representative"),
                            ("EMPLOYEE_REP", "Employee Representative"),
                            ("UNION_REP", "Union Representative"),
                            ("OBSERVER", "Observer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=100)),
                ("appointed_date", models.DateField(blank=True, null=True)),
                ("term_end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("receives_meeting_invites", models.BooleanField(default=True)),
                (
                    "committee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="corporate.trainingcommittee",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_committee_memberships",
                        to="corporate.corporatecontact",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Committee Member",
                "verbose_name_plural": "Committee Members",
                "ordering": ["role", "name"],
            },
        ),
        migrations.CreateModel(
            name="TCMeetingAgendaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("duration_minutes", models.PositiveIntegerField(default=15)),
                (
                    "supporting_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="training_committees/agenda_documents/",
                    ),
                ),
                ("is_discussed", models.BooleanField(default=False)),
                ("discussion_notes", models.TextField(blank=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tc_agenda_items",
                        to="corporate.trainingcommitteemeeting",
                    ),
                ),
                (
                    "presenter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tc_presenting_items",
                        to="corporate.trainingcommitteemember",
                    ),
                ),
            ],
            options={
                "verbose_name": "TC Agenda Item",
                "verbose_name_plural": "TC Agenda Items",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="TCMeetingActionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField()),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("DEFERRED", "Deferred"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="OPEN",
                        max_length=15,
                    ),
                ),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("completion_notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "agenda_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tc_action_items",
                        to="corporate.tcmeetingagendaitem",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tc_action_items",
                        to="corporate.trainingcommitteemeeting",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tc_assigned_actions",
                        to="corporate.trainingcommitteemember",
                    ),
                ),
            ],
            options={
                "verbose_name": "TC Action Item",
                "verbose_name_plural": "TC Action Items",
                "ordering": ["-priority", "due_date"],
            },
        ),
        migrations.CreateModel(
            name="MeetingMinutes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("opening_remarks", models.TextField(blank=True)),
                (
                    "matters_arising",
                    models.TextField(
                        blank=True, help_text="Matters arising from previous minutes"
                    ),
                ),
                ("general_discussion", models.TextField(blank=True)),
                ("closing_remarks", models.TextField(blank=True)),
                ("next_meeting_date", models.DateField(blank=True, null=True)),
                ("next_meeting_notes", models.TextField(blank=True)),
                (
                    "minutes_document",
                    models.FileField(
                        blank=True, null=True, upload_to="training_committees/minutes/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("approved_date", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meeting",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="minutes",
                        to="corporate.trainingcommitteemeeting",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_minutes",
                        to="corporate.trainingcommitteemember",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting Minutes",
                "verbose_name_plural": "Meeting Minutes",
            },
        ),
        migrations.CreateModel(
            name="WSPATRServiceYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "financial_year",
                    models.PositiveIntegerField(
                        help_text="Financial year start (e.g., 2024 for Apr 2024 - Mar 2025)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("DATA_COLLECTION", "Data Collection"),
                            ("DRAFTING", "Drafting"),
                            ("INTERNAL_REVIEW", "Internal Review"),
                            ("CLIENT_REVIEW", "Client Review"),
                            ("SUBMITTED", "Submitted to SETA"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected - Resubmission Required"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="NOT_STARTED",
                        max_length=30,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("APPROVED_CONDITIONS", "Approved with Conditions"),
                            ("REJECTED", "Rejected"),
                            ("NOT_SUBMITTED", "Not Submitted"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                (
                    "submission_deadline",
                    models.DateField(
                        help_text="SETA submission deadline (typically 30 April)"
                    ),
                ),
                ("submitted_date", models.DateField(blank=True, null=True)),
                ("outcome_date", models.DateField(blank=True, null=True)),
                ("seta_reference", models.CharField(blank=True, max_length=100)),
                ("seta_feedback", models.TextField(blank=True)),
                (
                    "progress_percentage",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_consultant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_wspatr_years",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "atr_submission",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_year",
                        to="corporate.atrsubmission",
                    ),
                ),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_items",
                        to="tenants.campus",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wspatr_service_years",
                        to="corporate.corporateclient",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wspatr_service_years",
                        to="learners.seta",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wspatr_years",
                        to="corporate.clientservicesubscription",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wsp_submission",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_year",
                        to="corporate.wspsubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "WSP/ATR Service Year",
                "verbose_name_plural": "WSP/ATR Service Years",
                "ordering": ["-financial_year", "client__company_name"],
                "unique_together": {("subscription", "financial_year")},
            },
        ),
        migrations.CreateModel(
            name="WSPATRPivotalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pivotal_type",
                    models.CharField(
                        choices=[
                            ("LEARNERSHIP_18_1", "Learnership 18.1 (Employed)"),
                            ("LEARNERSHIP_18_2", "Learnership 18.2 (Unemployed)"),
                            ("SKILLS_PROGRAMME", "Skills Programme"),
                            ("APPRENTICESHIP", "Apprenticeship"),
                            ("INTERNSHIP", "Internship"),
                            ("BURSARY_EMPLOYED", "Bursary (Employed)"),
                            ("BURSARY_UNEMPLOYED", "Bursary (Unemployed)"),
                            ("CANDIDACY", "Candidacy Programme"),
                            ("WIL", "Work Integrated Learning"),
                        ],
                        max_length=30,
                    ),
                ),
                ("programme_name", models.CharField(max_length=200)),
                ("planned_beneficiaries", models.PositiveIntegerField(default=0)),
                ("actual_beneficiaries", models.PositiveIntegerField(default=0)),
                (
                    "planned_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "service_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pivotal_data",
                        to="corporate.wspatrserviceyear",
                    ),
                ),
            ],
            options={
                "verbose_name": "WSP/ATR PIVOTAL Data",
                "verbose_name_plural": "WSP/ATR PIVOTAL Data",
                "ordering": ["pivotal_type"],
            },
        ),
        migrations.AddField(
            model_name="trainingcommitteemeeting",
            name="service_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="committee_meetings",
                to="corporate.wspatrserviceyear",
            ),
        ),
        migrations.CreateModel(
            name="WSPATRTrainingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[("PLANNED", "WSP Planned"), ("ACTUAL", "ATR Actual")],
                        max_length=10,
                    ),
                ),
                (
                    "intervention_type",
                    models.CharField(
                        choices=[
                            ("LEARNERSHIP", "Learnership"),
                            ("SKILLS_PROGRAMME", "Skills Programme"),
                            ("APPRENTICESHIP", "Apprenticeship"),
                            ("INTERNSHIP", "Internship"),
                            ("BURSARY", "Bursary"),
                            ("SHORT_COURSE", "Short Course"),
                            ("ARTISAN", "Artisan Development"),
                            ("AET", "Adult Education & Training"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("programme_name", models.CharField(max_length=200)),
                ("nqf_level", models.PositiveIntegerField(blank=True, null=True)),
                ("african_male", models.PositiveIntegerField(default=0)),
                ("african_female", models.PositiveIntegerField(default=0)),
                ("coloured_male", models.PositiveIntegerField(default=0)),
                ("coloured_female", models.PositiveIntegerField(default=0)),
                ("indian_male", models.PositiveIntegerField(default=0)),
                ("indian_female", models.PositiveIntegerField(default=0)),
                ("white_male", models.PositiveIntegerField(default=0)),
                ("white_female", models.PositiveIntegerField(default=0)),
                ("disabled_male", models.PositiveIntegerField(default=0)),
                ("disabled_female", models.PositiveIntegerField(default=0)),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "qualification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wspatr_training_data",
                        to="academics.qualification",
                    ),
                ),
                (
                    "service_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_data",
                        to="corporate.wspatrserviceyear",
                    ),
                ),
            ],
            options={
                "verbose_name": "WSP/ATR Training Data",
                "verbose_name_plural": "WSP/ATR Training Data",
                "ordering": ["data_type", "intervention_type"],
            },
        ),
        migrations.CreateModel(
            name="TCMeetingAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INVITED", "Invited"),
                            ("CONFIRMED", "Confirmed"),
                            ("ATTENDED", "Attended"),
                            ("APOLOGIES", "Apologies"),
                            ("ABSENT", "Absent"),
                        ],
                        default="INVITED",
                        max_length=15,
                    ),
                ),
                ("invite_sent", models.BooleanField(default=False)),
                ("invite_sent_date", models.DateTimeField(blank=True, null=True)),
                ("invite_response_date", models.DateTimeField(blank=True, null=True)),
                ("arrival_time", models.TimeField(blank=True, null=True)),
                ("departure_time", models.TimeField(blank=True, null=True)),
                (
                    "signature_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="training_committees/signatures/",
                    ),
                ),
                ("signed_date", models.DateTimeField(blank=True, null=True)),
                ("apology_reason", models.TextField(blank=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tc_attendance_records",
                        to="corporate.trainingcommitteemeeting",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tc_attendance_records",
                        to="corporate.trainingcommitteemember",
                    ),
                ),
            ],
            options={
                "verbose_name": "TC Meeting Attendance",
                "verbose_name_plural": "TC Meeting Attendance Records",
                "ordering": ["member__role"],
                "unique_together": {("meeting", "member")},
            },
        ),
        migrations.CreateModel(
            name="WSPATREmployeeData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "occupational_level",
                    models.CharField(
                        choices=[
                            ("TOP_MANAGEMENT", "Top Management"),
                            ("SENIOR_MANAGEMENT", "Senior Management"),
                            ("PROFESSIONAL", "Professionally Qualified"),
                            ("SKILLED_TECHNICAL", "Skilled Technical"),
                            ("SEMI_SKILLED", "Semi-Skilled"),
                            ("UNSKILLED", "Unskilled"),
                        ],
                        max_length=30,
                    ),
                ),
                ("african_male", models.PositiveIntegerField(default=0)),
                ("coloured_male", models.PositiveIntegerField(default=0)),
                ("indian_male", models.PositiveIntegerField(default=0)),
                ("white_male", models.PositiveIntegerField(default=0)),
                ("foreign_male", models.PositiveIntegerField(default=0)),
                ("african_female", models.PositiveIntegerField(default=0)),
                ("coloured_female", models.PositiveIntegerField(default=0)),
                ("indian_female", models.PositiveIntegerField(default=0)),
                ("white_female", models.PositiveIntegerField(default=0)),
                ("foreign_female", models.PositiveIntegerField(default=0)),
                ("disabled_male", models.PositiveIntegerField(default=0)),
                ("disabled_female", models.PositiveIntegerField(default=0)),
                (
                    "service_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_data",
                        to="corporate.wspatrserviceyear",
                    ),
                ),
            ],
            options={
                "verbose_name": "WSP/ATR Employee Data",
                "verbose_name_plural": "WSP/ATR Employee Data",
                "ordering": ["occupational_level"],
                "unique_together": {("service_year", "occupational_level")},
            },
        ),
    ]
