# Generated by Django 5.2.8 on 2025-12-19 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0011_wspatr_service_enhancement"),
        ("learners", "0003_guardian"),
        ("tenants", "0002_extend_campus_code_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicedeliverytemplate",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("WSP_ATR", "WSP/ATR (Full Package)"),
                    ("BEE_CONSULTING", "BEE Consulting & Preparation"),
                    ("EE_CONSULTING", "Employment Equity (Full Package)"),
                    ("HOST_EMPLOYMENT", "Host Employment"),
                    ("DG_APPLICATION", "Discretionary Grant Applications"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="serviceoffering",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("WSP_ATR", "WSP/ATR (Full Package)"),
                    ("BEE_CONSULTING", "BEE Consulting & Preparation"),
                    ("EE_CONSULTING", "Employment Equity (Full Package)"),
                    ("HOST_EMPLOYMENT", "Host Employment"),
                    ("DG_APPLICATION", "Discretionary Grant Applications"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="WSPATRDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("SDL_CERTIFICATE", "SDL Certificate"),
                            ("COMPANY_REGISTRATION", "Company Registration (CIPC)"),
                            ("BEE_CERTIFICATE", "B-BBEE Certificate"),
                            ("TAX_CLEARANCE", "Tax Clearance Certificate"),
                            ("EMPLOYEE_LIST", "Employee List/Headcount"),
                            ("TRAINING_PLAN", "Training Plan"),
                            ("TRAINING_BUDGET", "Training Budget"),
                            ("COMMITTEE_MINUTES", "Training Committee Minutes"),
                            (
                                "COMMITTEE_ATTENDANCE",
                                "Training Committee Attendance Register",
                            ),
                            ("ATR_EVIDENCE", "ATR Training Evidence/POE"),
                            ("PIVOTAL_EVIDENCE", "PIVOTAL Training Evidence"),
                            ("SKILLS_AUDIT", "Skills Audit Report"),
                            ("ORGANOGRAM", "Company Organogram"),
                            ("SIGNED_WSP", "Signed WSP Document"),
                            ("SIGNED_ATR", "Signed ATR Document"),
                            ("APPROVAL_LETTER", "WSP Approval Letter from SETA"),
                            ("GRANT_LETTER", "Mandatory Grant Letter"),
                            ("REJECTION_LETTER", "Rejection/Query Letter"),
                            ("SUBMISSION_RECEIPT", "Submission Receipt/Confirmation"),
                            ("OTHER", "Other Document"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Custom document name (optional)",
                        max_length=200,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="wspatr_documents/%Y/%m/"
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("is_required", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Upload"),
                            ("UPLOADED", "Uploaded"),
                            ("APPROVED", "Approved/Verified"),
                            ("REJECTED", "Rejected - Reupload Required"),
                            ("NOT_APPLICABLE", "Not Applicable"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_items",
                        to="tenants.campus",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_wspatr_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="corporate.wspatrserviceyear",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_wspatr_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "WSP/ATR Document",
                "verbose_name_plural": "WSP/ATR Documents",
                "ordering": ["sort_order", "document_type"],
            },
        ),
        migrations.CreateModel(
            name="WSPATRDocumentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "required_documents",
                    models.JSONField(
                        default=list,
                        help_text="List of required document types and their settings",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_items",
                        to="tenants.campus",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seta",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for default template",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wspatr_document_templates",
                        to="learners.seta",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "WSP/ATR Document Template",
                "verbose_name_plural": "WSP/ATR Document Templates",
                "ordering": ["seta__name", "name"],
            },
        ),
    ]
