# Generated by Django 5.2.8 on 2025-12-20 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0012_alter_servicedeliverytemplate_service_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="corporateemployee",
            name="employment_type",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="corporateemployee",
            name="occupational_level",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="corporateemployee",
            name="ofo_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="employeeidp",
            name="service_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="idps",
                to="corporate.wspatrserviceyear",
            ),
        ),
        migrations.AddField(
            model_name="idptrainingneed",
            name="is_wsp_planned",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this will be pulled into the WSP submission for the linked service year.",
                verbose_name="Include in WSP Planned Training",
            ),
        ),
        migrations.AddField(
            model_name="wspatrdocument",
            name="meeting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wspatr_documents",
                to="corporate.trainingcommitteemeeting",
            ),
        ),
        migrations.AlterField(
            model_name="wspatrserviceyear",
            name="financial_year",
            field=models.PositiveIntegerField(
                help_text="Financial year start (e.g., 2024 for 1 May 2024 - 30 April 2025)"
            ),
        ),
    ]
