# Generated by Django 5.2.8 on 2025-12-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0013_corporateemployee_employment_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostemployer",
            name="geofence_radius_meters",
            field=models.IntegerField(
                default=5000,
                help_text="Geofence radius in meters for attendance verification (default: 5000m = 5km)",
            ),
        ),
        migrations.AddField(
            model_name="hostemployer",
            name="gps_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="GPS latitude of workplace location",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hostemployer",
            name="gps_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="GPS longitude of workplace location",
                max_digits=9,
                null=True,
            ),
        ),
    ]
