# Generated by Django 5.2.8 on 2026-01-03 20:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0014_add_geofencing_to_host_employer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hostmentor',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hostmentor',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostmentor',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_mentors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hostmentor',
            name='cv_document',
            field=models.FileField(blank=True, upload_to='mentor_documents/cv/'),
        ),
        migrations.AddField(
            model_name='hostmentor',
            name='cv_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostmentor',
            name='cv_uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_mentor_cvs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hostmentor',
            name='id_copy',
            field=models.FileField(blank=True, upload_to='mentor_documents/id/'),
        ),
        migrations.AddField(
            model_name='hostmentor',
            name='id_copy_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostmentor',
            name='id_copy_uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_mentor_ids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hostmentor',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text='List of languages spoken'),
        ),
        migrations.AddField(
            model_name='hostmentor',
            name='red_seal_certificate',
            field=models.FileField(blank=True, upload_to='mentor_documents/certificates/'),
        ),
        migrations.AddField(
            model_name='hostmentor',
            name='red_seal_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostmentor',
            name='red_seal_uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_mentor_red_seals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hostmentor',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('INACTIVE', 'Inactive')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='hostmentor',
            name='mentor_certificate',
            field=models.FileField(blank=True, upload_to='mentor_documents/certificates/'),
        ),
        migrations.CreateModel(
            name='MentorInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('created_mentor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation', to='corporate.hostmentor')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_invitations', to='corporate.hostemployer')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_mentor_invitations', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentor Invitation',
                'verbose_name_plural': 'Mentor Invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_file', models.FileField(upload_to='placement_invoices/')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='DRAFT', max_length=20)),
                ('approval_method', models.CharField(blank=True, choices=[('CLIENT', 'Approved by Client'), ('ADMIN_ON_BEHALF', 'Approved by Admin on Behalf of Client')], max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_screenshot', models.FileField(blank=True, help_text='Required when admin approves on behalf of client (screenshot of email approval)', upload_to='placement_invoices/approval_screenshots/')),
                ('rejection_reason', models.TextField(blank=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_placement_invoices', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='corporate.workplaceplacement')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_placement_invoices', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Placement Invoice',
                'verbose_name_plural': 'Placement Invoices',
                'ordering': ['-invoice_date'],
            },
        ),
    ]
