# Generated by Django 5.2.8 on 2026-01-08 20:58

import corporate.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0015_hostmentor_additional_notes_hostmentor_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatecontact',
            name='can_complete_deliverables',
            field=models.BooleanField(default=False, help_text='Can mark service deliverables/tasks as complete'),
        ),
        migrations.AddField(
            model_name='corporatecontact',
            name='can_upload_evidence',
            field=models.BooleanField(default=False, help_text='Can upload evidence files for deliverables'),
        ),
        migrations.AddField(
            model_name='milestonetask',
            name='client_visible',
            field=models.BooleanField(default=True, help_text='Show this task in client portal'),
        ),
        migrations.AddField(
            model_name='milestonetask',
            name='completed_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who marked this task complete', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_milestone_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='milestonetask',
            name='completed_by_contact',
            field=models.ForeignKey(blank=True, help_text='Client contact who marked this task complete', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to='corporate.corporatecontact'),
        ),
        migrations.AddField(
            model_name='milestonetask',
            name='completion_notes',
            field=models.TextField(blank=True, help_text='Notes added when task was completed'),
        ),
        migrations.AddField(
            model_name='milestonetask',
            name='requires_evidence',
            field=models.BooleanField(default=False, help_text='This task requires evidence upload for completion'),
        ),
        migrations.CreateModel(
            name='TaskEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Name/description of this evidence', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(help_text='Allowed: PDF, Word, Excel, Images (JPG, PNG, GIF)', upload_to='task_evidence/', validators=[corporate.models.validate_evidence_file_extension])),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='corporate.milestonetask')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='Staff member who uploaded this evidence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_task_evidence', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by_contact', models.ForeignKey(blank=True, help_text='Client contact who uploaded this evidence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidence', to='corporate.corporatecontact')),
            ],
            options={
                'verbose_name': 'Task Evidence',
                'verbose_name_plural': 'Task Evidence',
                'ordering': ['-created_at'],
            },
        ),
    ]
