# Generated by Django 5.2.8 on 2026-01-27 09:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0019_digital_signature'),
        ('tenants', '0002_extend_campus_code_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('legacy_onboarding', models.BooleanField(default=False, help_text='True if this is a legacy client onboarded before this system')),
                ('current_step', models.CharField(choices=[('COMPANY_VERIFY', 'Company Verification'), ('SERVICES', 'Services Configuration'), ('CONTACTS', 'Contacts & Portal Access'), ('DOCUMENTS', 'Document Initialization'), ('KICKOFF', 'Kickoff Meeting'), ('COMPLETE', 'Onboarding Complete')], default='COMPANY_VERIFY', max_length=20)),
                ('step_statuses', models.JSONField(default=dict)),
                ('company_verified', models.BooleanField(default=False)),
                ('company_verified_at', models.DateTimeField(blank=True, null=True)),
                ('services_configured', models.BooleanField(default=False)),
                ('contacts_invited', models.BooleanField(default=False)),
                ('documents_initialized', models.BooleanField(default=False)),
                ('kickoff_scheduled', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('account_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_onboardings', to=settings.AUTH_USER_MODEL)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='tenants.campus')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='corporate.corporateclient')),
                ('company_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('kickoff_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kickoff_onboardings', to='corporate.trainingcommitteemeeting')),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_onboardings', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Onboarding',
                'verbose_name_plural': 'Client Onboardings',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('SDF', 'Skills Development Facilitator'), ('HR_MANAGER', 'HR Manager'), ('TRAINING_MANAGER', 'Training Manager'), ('FINANCE', 'Finance Contact'), ('SENIOR_MANAGER', 'Senior Manager'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('permission_template', models.CharField(choices=[('FULL_ACCESS', 'Full Access'), ('VIEW_ONLY', 'View Only'), ('SDF_STANDARD', 'SDF Standard'), ('HR_STANDARD', 'HR Standard')], default='VIEW_ONLY', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='PENDING', max_length=20)),
                ('personal_message', models.TextField(blank=True, help_text='Optional personal message in invitation email')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='tenants.campus')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_invitations', to='corporate.corporateclient')),
                ('contact', models.ForeignKey(blank=True, help_text='Contact created on invitation acceptance', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portal_invitations', to='corporate.corporatecontact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portal Invitation',
                'verbose_name_plural': 'Portal Invitations',
                'ordering': ['-invited_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('service_type', models.CharField(choices=[('WSP_ATR', 'WSP/ATR'), ('EE', 'Employment Equity'), ('BBBEE', 'B-BBEE'), ('HOST_EMPLOYMENT', 'Host Employment'), ('DG_APPLICATION', 'Discretionary Grant')], max_length=20)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete')], default='NOT_STARTED', max_length=20)),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('total_steps', models.PositiveIntegerField(default=1)),
                ('step_data', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_onboardings', to=settings.AUTH_USER_MODEL)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='tenants.campus')),
                ('client_onboarding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_onboardings', to='corporate.clientonboarding')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='corporate.clientservicesubscription')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Onboarding',
                'verbose_name_plural': 'Service Onboardings',
                'ordering': ['subscription__client__company_name', 'service_type'],
            },
        ),
    ]
