# Generated by Django 5.2.8 on 2026-01-27 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0020_add_onboarding_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedeliveryproject',
            name='implementation_year',
            field=models.PositiveIntegerField(blank=True, help_text='Implementation year cycle e.g. 2024, 2025', null=True),
        ),
        migrations.AlterField(
            model_name='servicedeliveryproject',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='servicedeliveryproject',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_delivery_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
