# Generated by Django 5.2.8 on 2026-01-27 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0021_service_delivery_project_optional_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eeserviceyear',
            unique_together={('client', 'reporting_year')},
        ),
        migrations.AlterUniqueTogether(
            name='wspatrserviceyear',
            unique_together={('client', 'financial_year')},
        ),
        migrations.AlterField(
            model_name='eeserviceyear',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ee_service_years', to='corporate.clientservicesubscription'),
        ),
        migrations.AlterField(
            model_name='wspatrserviceyear',
            name='submission_deadline',
            field=models.DateField(blank=True, help_text='SETA submission deadline (typically 30 April)', null=True),
        ),
        migrations.AlterField(
            model_name='wspatrserviceyear',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wspatr_years', to='corporate.clientservicesubscription'),
        ),
    ]
