# Generated by Django 5.2.8 on 2026-01-27 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0022_alter_eeserviceyear_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bbbeeserviceyear',
            unique_together={('client', 'financial_year')},
        ),
        migrations.AlterField(
            model_name='bbbeeserviceyear',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bbbee_service_years', to='corporate.clientservicesubscription'),
        ),
    ]
