# Generated by Django 5.2.8 on 2026-01-17 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('tenants', '0002_extend_campus_code_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='primary_work_location',
            field=models.ForeignKey(blank=True, help_text='Primary work location/campus for this staff member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_staff', to='tenants.campus'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='work_locations',
            field=models.ManyToManyField(blank=True, help_text='Campuses/locations where this staff member works', related_name='assigned_staff', to='tenants.campus'),
        ),
    ]
