# Generated by Django 6.0.1 on 2026-02-02 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_add_work_location_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('leave_type', models.CharField(choices=[('ANNUAL', 'Annual Leave'), ('SICK', 'Sick Leave'), ('FAMILY', 'Family Responsibility Leave'), ('STUDY', 'Study Leave'), ('UNPAID', 'Unpaid Leave')], help_text='Type of leave being requested', max_length=20)),
                ('start_date', models.DateField(help_text='First day of leave')),
                ('end_date', models.DateField(help_text='Last day of leave')),
                ('days_requested', models.DecimalField(decimal_places=1, help_text='Number of working days requested (supports half-days)', max_digits=5)),
                ('reason', models.TextField(blank=True, help_text='Reason for leave request')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the leave request', max_length=20)),
                ('approved_date', models.DateTimeField(blank=True, help_text='Date and time the request was approved or rejected', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if applicable)')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Manager who approved or rejected the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_approvals', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('staff_profile', models.ForeignKey(help_text='Staff member requesting leave', on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hr.staffprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Request',
                'verbose_name_plural': 'Leave Requests',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['staff_profile', 'status'], name='hr_leavereq_staff_p_4f2a81_idx'), models.Index(fields=['start_date', 'end_date'], name='hr_leavereq_start_d_9e9e54_idx')],
            },
        ),
        migrations.CreateModel(
            name='StaffDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(help_text='Document title (e.g., Employment Contract 2024)', max_length=255)),
                ('document_type', models.CharField(choices=[('CONTRACT', 'Employment Contract'), ('ID', 'ID Document'), ('QUALIFICATION', 'Qualification'), ('CERTIFICATE', 'Certificate'), ('OTHER', 'Other')], help_text='Category of document', max_length=20)),
                ('file', models.FileField(help_text='Uploaded document file', upload_to='hr/staff_documents/%Y/%m/')),
                ('expiry_date', models.DateField(blank=True, help_text='Document expiry date (leave blank if not applicable)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this document')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('staff_profile', models.ForeignKey(help_text='Staff member this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hr.staffprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Document',
                'verbose_name_plural': 'Staff Documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['staff_profile', 'document_type'], name='hr_staffdoc_staff_p_a65117_idx'), models.Index(fields=['expiry_date'], name='hr_staffdoc_expiry__543bc6_idx')],
            },
        ),
    ]
