# Generated by Django 5.2.8 on 2025-12-08 13:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0004_year_based_progress"),
        ("core", "0012_add_recurring_deliverables"),
        ("corporate", "0010_alter_legacytradetestappeal_options_and_more"),
        ("finance", "0003_bursaryprovider_bursaryapplication_debitordermandate"),
        ("learners", "0003_guardian"),
        ("logistics", "0001_initial"),
        ("tenants", "0002_extend_campus_code_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Intake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique intake code e.g. INT-2025-001",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "delivery_mode",
                    models.CharField(
                        choices=[
                            ("ON_CAMPUS", "On Campus"),
                            ("OFF_SITE", "Off-Site / Client Premises"),
                            ("ONLINE", "Online"),
                            ("BLENDED", "Blended"),
                            ("WORKPLACE", "Workplace Based"),
                        ],
                        default="ON_CAMPUS",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "enrollment_deadline",
                    models.DateField(
                        blank=True, help_text="Last date to enroll learners", null=True
                    ),
                ),
                (
                    "max_capacity",
                    models.PositiveIntegerField(
                        default=30, help_text="Maximum learners for this intake"
                    ),
                ),
                (
                    "min_viable",
                    models.PositiveIntegerField(
                        default=10, help_text="Minimum learners needed to run"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("RECRUITING", "Recruiting"),
                            ("ENROLLMENT_OPEN", "Enrollment Open"),
                            ("ENROLLMENT_CLOSED", "Enrollment Closed"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
                (
                    "registration_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "tuition_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "materials_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="intakes",
                        to="tenants.campus",
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intake_records",
                        to="logistics.cohort",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facilitator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="facilitated_intakes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "not_intake",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific NOT intake phase this relates to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intake_bucket",
                        to="core.notintake",
                    ),
                ),
                (
                    "qualification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="intakes",
                        to="academics.qualification",
                    ),
                ),
                (
                    "training_notification",
                    models.ForeignKey(
                        blank=True,
                        help_text="NOT that created this intake (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intake_records",
                        to="core.trainingnotification",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intakes",
                        to="logistics.venue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intake",
                "verbose_name_plural": "Intakes",
                "ordering": ["-start_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="IntakeEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment_number",
                    models.CharField(blank=True, max_length=30, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPLIED", "Applied"),
                            ("DOC_CHECK", "Document Verification"),
                            ("PAYMENT_PENDING", "Payment Pending"),
                            ("ENROLLED", "Enrolled"),
                            ("ACTIVE", "Active"),
                            ("ON_HOLD", "On Hold"),
                            ("COMPLETED", "Completed"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="APPLIED",
                        max_length=20,
                    ),
                ),
                (
                    "funding_type",
                    models.CharField(
                        choices=[
                            ("SELF_FUNDED", "Self-Funded"),
                            ("PARENT_FUNDED", "Parent/Guardian Funded"),
                            ("EMPLOYER_FUNDED", "Employer Funded"),
                            ("BURSARY", "Bursary"),
                            ("STUDENT_LOAN", "Student Loan"),
                            ("SETA_FUNDED", "SETA Funded"),
                            ("DISCRETIONARY_GRANT", "Discretionary Grant"),
                            ("PIVOTAL_GRANT", "PIVOTAL Grant"),
                            ("MIXED", "Mixed Funding"),
                        ],
                        default="SELF_FUNDED",
                        max_length=25,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FULL_UPFRONT", "Full Payment Upfront"),
                            ("INSTALMENT", "Instalment Plan"),
                            ("DEBIT_ORDER", "Debit Order"),
                            ("CORPORATE_INVOICE", "Corporate Invoice"),
                            ("SETA_TRANCHE", "SETA Tranche Payment"),
                            ("BURSARY_DISBURSEMENT", "Bursary Disbursement"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "registration_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "tuition_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "materials_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("discount_reason", models.CharField(blank=True, max_length=200)),
                ("registration_paid", models.BooleanField(default=False)),
                ("registration_paid_date", models.DateField(blank=True, null=True)),
                (
                    "registration_payment_reference",
                    models.CharField(blank=True, max_length=100),
                ),
                ("bursary_contract_signed", models.BooleanField(default=False)),
                ("bursary_contract_date", models.DateField(blank=True, null=True)),
                (
                    "bursary_contract_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="intake_enrollments/bursary_contracts/",
                    ),
                ),
                ("application_date", models.DateField(auto_now_add=True)),
                ("enrollment_date", models.DateField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("withdrawal_date", models.DateField(blank=True, null=True)),
                ("withdrawal_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "academic_enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intake_enrollment",
                        to="academics.enrollment",
                    ),
                ),
                (
                    "bursary_application",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked bursary application if bursary-funded",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollments",
                        to="finance.bursaryapplication",
                    ),
                ),
                (
                    "corporate_client",
                    models.ForeignKey(
                        blank=True,
                        help_text="Corporate client if employer-funded",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sponsored_enrollments",
                        to="corporate.corporateclient",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "debit_order_mandate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollments",
                        to="finance.debitordermandate",
                    ),
                ),
                (
                    "intake",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="intakes.intake",
                    ),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intake_enrollments",
                        to="learners.learner",
                    ),
                ),
                (
                    "responsible_payer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Guardian/parent responsible for payment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paid_enrollments",
                        to="learners.guardian",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Intake Enrollment",
                "verbose_name_plural": "Intake Enrollments",
                "ordering": ["-application_date"],
                "unique_together": {("intake", "learner")},
            },
        ),
        migrations.CreateModel(
            name="IntakeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("ID_DOCUMENT", "ID Document"),
                            ("PASSPORT", "Passport"),
                            ("BIRTH_CERTIFICATE", "Birth Certificate"),
                            ("MATRIC_CERTIFICATE", "Matric Certificate"),
                            ("HIGHEST_QUALIFICATION", "Highest Qualification"),
                            ("PROOF_OF_PAYMENT", "Proof of Payment"),
                            ("BURSARY_CONTRACT", "Bursary Contract"),
                            ("DEBIT_ORDER_MANDATE", "Debit Order Mandate"),
                            ("PARENT_CONSENT", "Parent/Guardian Consent"),
                            ("MEDICAL_CERTIFICATE", "Medical Certificate"),
                            ("EMPLOYMENT_CONFIRMATION", "Employment Confirmation"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file", models.FileField(upload_to="intake_documents/")),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_intake_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="intakes.intakeenrollment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intake Document",
                "verbose_name_plural": "Intake Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IntakeCapacitySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField()),
                ("max_capacity", models.PositiveIntegerField()),
                ("enrolled_count", models.PositiveIntegerField()),
                ("pending_count", models.PositiveIntegerField()),
                ("withdrawn_count", models.PositiveIntegerField(default=0)),
                (
                    "fill_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("self_funded_count", models.PositiveIntegerField(default=0)),
                ("parent_funded_count", models.PositiveIntegerField(default=0)),
                ("employer_funded_count", models.PositiveIntegerField(default=0)),
                ("bursary_count", models.PositiveIntegerField(default=0)),
                ("seta_funded_count", models.PositiveIntegerField(default=0)),
                ("other_funded_count", models.PositiveIntegerField(default=0)),
                (
                    "intake",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capacity_snapshots",
                        to="intakes.intake",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intake Capacity Snapshot",
                "verbose_name_plural": "Intake Capacity Snapshots",
                "ordering": ["-snapshot_date"],
                "unique_together": {("intake", "snapshot_date")},
            },
        ),
    ]
