# Generated by Django 5.2.8 on 2025-12-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intakes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intakeenrollment",
            name="funding_type",
            field=models.CharField(
                choices=[
                    ("SELF_FUNDED", "Self-Funded"),
                    ("PARENT_FUNDED", "Parent/Guardian Funded"),
                    ("EMPLOYER_FUNDED", "Employer Funded"),
                    ("BURSARY", "Bursary"),
                    ("LEARNER_LOAN", "Learner Loan"),
                    ("SETA_FUNDED", "SETA Funded"),
                    ("DISCRETIONARY_GRANT", "Discretionary Grant"),
                    ("PIVOTAL_GRANT", "PIVOTAL Grant"),
                    ("MIXED", "Mixed Funding"),
                ],
                default="SELF_FUNDED",
                max_length=25,
            ),
        ),
    ]
