# Generated by Django 5.2.8 on 2026-01-21 16:03

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_set_existing_accreditations_active'),
        ('core', '0023_project_template_sets'),
        ('corporate', '0019_digital_signature'),
        ('intakes', '0002_alter_intakeenrollment_funding_type'),
        ('learners', '0014_dailylogbookentry_attendance_record'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_number', models.CharField(blank=True, help_text='Unique contract reference number', max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('funder_type', models.CharField(choices=[('SETA', 'SETA'), ('CORPORATE', 'Corporate'), ('GOVERNMENT', 'Government'), ('MUNICIPALITY', 'Municipality'), ('PRIVATE', 'Private'), ('MIXED', 'Mixed Funding')], default='SETA', max_length=20)),
                ('contract_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('signature_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_SIGNATURE', 'Pending Signature'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20)),
                ('original_learner_count', models.PositiveIntegerField(default=0, help_text='Total learners contracted at the start')),
                ('max_dropout_percentage', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Maximum allowed dropout percentage (default 10%)', max_digits=5)),
                ('dropout_alert_threshold', models.DecimalField(decimal_places=2, default=Decimal('7.00'), help_text='Alert threshold for dropout percentage (default 7%)', max_digits=5)),
                ('contract_document', models.FileField(blank=True, null=True, upload_to='contracts/documents/')),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='corporate.corporateclient')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('seta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='learners.seta')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearnerContractEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_original', models.BooleanField(default=True, help_text='True if this learner was part of the original cohort')),
                ('is_replacement', models.BooleanField(default=False, help_text='True if this learner is replacing a terminated learner')),
                ('enrollment_date', models.DateField(default=datetime.date.today, help_text='Date learner was enrolled in the contract')),
                ('termination_date', models.DateField(blank=True, help_text='Date of termination (if terminated)', null=True)),
                ('termination_reason', models.CharField(blank=True, choices=[('PERSONAL', 'Personal Reasons'), ('FINANCIAL', 'Financial Difficulties'), ('EMPLOYMENT', 'Found Employment'), ('RELOCATION', 'Relocated'), ('ACADEMIC', 'Academic Performance Issues'), ('DISCIPLINARY', 'Disciplinary Action'), ('HEALTH', 'Health/Medical Reasons'), ('DECEASED', 'Deceased'), ('ABSCONDED', 'Absconded/No Contact'), ('EMPLOYER_REQUEST', 'Employer Request'), ('OTHER', 'Other')], help_text='Reason for termination', max_length=20)),
                ('termination_details', models.TextField(blank=True, help_text='Additional details about the termination')),
                ('termination_letter', models.FileField(blank=True, help_text='Termination letter or supporting documentation', null=True, upload_to='contracts/terminations/')),
                ('notes', models.TextField(blank=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_enrollments', to='intakes.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(blank=True, help_text='Link to academic enrollment for NLRD tracking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_enrollment', to='academics.enrollment')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_enrollments', to='learners.learner')),
                ('replaces_learner', models.ForeignKey(blank=True, help_text='The learner this person is replacing (if replacement)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='intakes.learnercontractenrollment')),
                ('terminated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminated_contract_enrollments', to=settings.AUTH_USER_MODEL)),
                ('training_notification', models.ForeignKey(blank=True, help_text='Specific NOT this learner is enrolled in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_learner_enrollments', to='core.trainingnotification')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract Learner Enrollment',
                'verbose_name_plural': 'Contract Learner Enrollments',
                'ordering': ['-enrollment_date'],
                'unique_together': {('contract', 'learner')},
            },
        ),
    ]
