# Generated by Django 5.2.8 on 2026-02-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intakes', '0003_contract_and_learner_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intakeenrollment',
            name='funding_type',
            field=models.CharField(choices=[('PRIVATE_UPFRONT', 'Private - Upfront Payment'), ('PRIVATE_PMT_AGREEMENT', 'Private - Payment Agreement'), ('GOVERNMENT_BURSARY', 'Government Bursary'), ('CORPORATE_BURSARY', 'Corporate Bursary'), ('DG_BURSARY', 'DG Bursary'), ('SELF_FUNDED', 'Self-Funded'), ('PARENT_FUNDED', 'Parent/Guardian Funded'), ('EMPLOYER_FUNDED', 'Employer Funded'), ('BURSARY', 'Bursary'), ('LEARNER_LOAN', 'Learner Loan'), ('SETA_FUNDED', 'SETA Funded'), ('DISCRETIONARY_GRANT', 'Discretionary Grant'), ('PIVOTAL_GRANT', 'PIVOTAL Grant'), ('MIXED', 'Mixed Funding')], default='SELF_FUNDED', max_length=25),
        ),
    ]
