# Generated by Django 5.2.11 on 2026-02-12 05:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_name', models.CharField(max_length=150, unique=True)),
                ('module', models.CharField(choices=[('crm', 'CRM / Leads'), ('tenders', 'Tenders'), ('lms', 'LMS / Sync'), ('hr', 'HR'), ('finance', 'Finance'), ('other', 'Other')], default='crm', max_length=30)),
                ('title', models.CharField(default='Getting started', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords.', max_length=255),
        ),
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='module',
            field=models.CharField(choices=[('crm', 'CRM / Leads'), ('tenders', 'Tenders'), ('lms', 'LMS / Sync'), ('hr', 'HR'), ('finance', 'Finance'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='supportcategory',
            name='module',
            field=models.CharField(choices=[('crm', 'CRM / Leads'), ('tenders', 'Tenders'), ('lms', 'LMS / Sync'), ('hr', 'HR'), ('finance', 'Finance'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='first_response_breached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='first_response_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='module',
            field=models.CharField(choices=[('crm', 'CRM / Leads'), ('tenders', 'Tenders'), ('lms', 'LMS / Sync'), ('hr', 'HR'), ('finance', 'Finance'), ('other', 'Other')], default='crm', max_length=30),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='resolution_breached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='resolution_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='support.ticketmessage'),
        ),
        migrations.AddField(
            model_name='trainingguide',
            name='module',
            field=models.CharField(choices=[('crm', 'CRM / Leads'), ('tenders', 'Tenders'), ('lms', 'LMS / Sync'), ('hr', 'HR'), ('finance', 'Finance'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='supportcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Optional icon name / identifier.', max_length=80),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainingguide',
            name='content',
            field=models.TextField(help_text='Guide content (Markdown).'),
        ),
        migrations.CreateModel(
            name='OnboardingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('link_url', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='support.onboardingchecklist')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SLAEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_events', to='support.supportticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportRoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(choices=[('crm', 'CRM / Leads'), ('tenders', 'Tenders'), ('lms', 'LMS / Sync'), ('hr', 'HR'), ('finance', 'Finance'), ('other', 'Other')], max_length=30, unique=True)),
                ('group_name', models.CharField(help_text="Django Group name, e.g. 'Support - CRM'", max_length=150)),
                ('fallback_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_routing_fallbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupportSLAConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(choices=[('crm', 'CRM / Leads'), ('tenders', 'Tenders'), ('lms', 'LMS / Sync'), ('hr', 'HR'), ('finance', 'Finance'), ('other', 'Other')], default='crm', max_length=30)),
                ('priority', models.CharField(default='normal', max_length=20)),
                ('first_response_minutes', models.PositiveIntegerField(default=240)),
                ('resolution_minutes', models.PositiveIntegerField(default=2880)),
                ('auto_escalate_on_breach', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['module', 'priority'],
                'unique_together': {('module', 'priority')},
            },
        ),
        migrations.CreateModel(
            name='UserOnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_done', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='support.onboardingitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'item')},
            },
        ),
    ]
