# Generated by Django 5.2.8 on 2026-01-03 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0006_qctoassessmentcriteria"),
        ("assessments", "0003_year_based_progress"),
        ("lms_sync", "0001_initial"),
        ("tenants", "0002_extend_campus_code_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeThreshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pass_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        help_text="Minimum percentage to pass",
                        max_digits=5,
                    ),
                ),
                (
                    "is_global",
                    models.BooleanField(
                        default=False, help_text="Is this the global default threshold?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.OneToOneField(
                        blank=True,
                        help_text="Leave blank for global default",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_threshold",
                        to="tenants.brand",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="threshold_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Grade Threshold",
                "verbose_name_plural": "Grade Thresholds",
            },
        ),
        migrations.CreateModel(
            name="MoodleCourseActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moodle_id",
                    models.PositiveIntegerField(help_text="Activity ID from Moodle"),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("QUIZ", "Quiz"),
                            ("ASSIGN", "Assignment"),
                            ("LESSON", "Lesson"),
                            ("SCORM", "SCORM Package"),
                            ("WORKSHOP", "Workshop"),
                            ("CHOICE", "Choice"),
                            ("FORUM", "Forum"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "grade_max",
                    models.DecimalField(
                        decimal_places=2,
                        default=100.0,
                        help_text="Maximum grade for this activity",
                        max_digits=5,
                    ),
                ),
                ("last_synced", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="lms_sync.moodlecourse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Moodle Course Activity",
                "verbose_name_plural": "Moodle Course Activities",
                "ordering": ["course", "name"],
                "unique_together": {("course", "moodle_id")},
            },
        ),
        migrations.CreateModel(
            name="AssessmentMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ai_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="AI confidence score (0-100)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "ai_reasoning",
                    models.TextField(
                        blank=True,
                        help_text="AI explanation for this mapping suggestion",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment_activity",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to internal assessment activity",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lms_mappings",
                        to="assessments.assessmentactivity",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_mappings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "qcto_criteria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moodle_mappings",
                        to="academics.qctoassessmentcriteria",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_mappings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "moodle_activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria_mappings",
                        to="lms_sync.moodlecourseactivity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assessment Mapping",
                "verbose_name_plural": "Assessment Mappings",
                "ordering": ["-ai_confidence", "status", "-created_at"],
                "unique_together": {("moodle_activity", "qcto_criteria")},
            },
        ),
    ]
