# Generated by Django 5.2.8 on 2025-12-08 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learners", "0002_wbl_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("PARENT", "Parent"),
                            ("GUARDIAN", "Legal Guardian"),
                            ("SPONSOR", "Sponsor"),
                            ("EMPLOYER", "Employer Representative"),
                            ("SELF", "Self (Adult Learner)"),
                            ("SPOUSE", "Spouse"),
                            ("SIBLING", "Sibling"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MR", "Mr"),
                            ("MRS", "Mrs"),
                            ("MS", "Ms"),
                            ("MISS", "Miss"),
                            ("DR", "Dr"),
                            ("PROF", "Prof"),
                        ],
                        max_length=10,
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "id_number",
                    models.CharField(
                        blank=True, help_text="SA ID Number", max_length=13
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone_mobile", models.CharField(max_length=20)),
                ("phone_work", models.CharField(blank=True, max_length=20)),
                ("phone_home", models.CharField(blank=True, max_length=20)),
                (
                    "is_financially_responsible",
                    models.BooleanField(
                        default=False,
                        help_text="Is this person responsible for paying fees?",
                    ),
                ),
                (
                    "is_emergency_contact",
                    models.BooleanField(
                        default=False, help_text="Should be contacted in emergencies?"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Primary guardian/parent for communications",
                    ),
                ),
                ("consent_signed", models.BooleanField(default=False)),
                ("consent_date", models.DateTimeField(blank=True, null=True)),
                (
                    "consent_document",
                    models.FileField(
                        blank=True,
                        help_text="Signed consent form",
                        null=True,
                        upload_to="guardian_consents/",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guardians",
                        to="learners.address",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardians",
                        to="learners.learner",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Guardian",
                "verbose_name_plural": "Guardians",
                "ordering": ["-is_primary", "last_name", "first_name"],
            },
        ),
    ]
