# Generated by Django 5.2.8 on 2025-12-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learners", "0005_create_default_budget_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="workplaceattendance",
            name="client_uuid",
            field=models.UUIDField(
                blank=True,
                help_text="Client-generated UUID for offline deduplication",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workplaceattendance",
            name="gps_accuracy",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="GPS accuracy in meters",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workplaceattendance",
            name="gps_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="GPS latitude at clock-in",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workplaceattendance",
            name="gps_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="GPS longitude at clock-in",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workplaceattendance",
            name="gps_timestamp",
            field=models.DateTimeField(
                blank=True, help_text="When GPS coordinates were captured", null=True
            ),
        ),
        migrations.AddField(
            model_name="workplaceattendance",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Photo proof of attendance (selfie at workplace)",
                null=True,
                upload_to="attendance_photos/%Y/%m/%d/",
            ),
        ),
        migrations.AddField(
            model_name="workplaceattendance",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("SYNCED", "Synced"),
                    ("PENDING", "Pending Sync"),
                    ("FAILED", "Sync Failed"),
                ],
                default="SYNCED",
                max_length=20,
            ),
        ),
    ]
