# Generated by Django 5.2.8 on 2025-12-31 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learners", "0007_learner_profile_enhancements"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="learner",
            name="address_line1",
        ),
        migrations.RemoveField(
            model_name="learner",
            name="address_line2",
        ),
        migrations.RemoveField(
            model_name="learner",
            name="alternative_phone",
        ),
        migrations.RemoveField(
            model_name="learner",
            name="city",
        ),
        migrations.RemoveField(
            model_name="learner",
            name="emergency_contact_name",
        ),
        migrations.RemoveField(
            model_name="learner",
            name="emergency_contact_phone",
        ),
        migrations.RemoveField(
            model_name="learner",
            name="emergency_contact_relationship",
        ),
        migrations.RemoveField(
            model_name="learner",
            name="id_number",
        ),
        migrations.RemoveField(
            model_name="learner",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="learner",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="learner",
            name="profile_photo",
        ),
        migrations.RemoveField(
            model_name="learner",
            name="province",
        ),
        migrations.CreateModel(
            name="AttendanceAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the action was performed",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("VERIFY", "Verified"),
                            ("REJECT", "Rejected"),
                            ("OVERRIDE", "Override Applied"),
                            ("EDIT", "Field Edited"),
                            ("CREATE", "Record Created"),
                        ],
                        db_index=True,
                        help_text="Type of action performed",
                        max_length=20,
                    ),
                ),
                (
                    "field_changed",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Specific field that was changed (for EDIT/OVERRIDE actions)",
                        max_length=100,
                    ),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True, help_text="Previous value before change"
                    ),
                ),
                (
                    "new_value",
                    models.TextField(blank=True, help_text="New value after change"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes or reason for change"
                    ),
                ),
                (
                    "action_gps_latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="GPS latitude where action was performed",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "action_gps_longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="GPS longitude where action was performed",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "archived",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Archived logs moved to cold storage",
                    ),
                ),
                (
                    "attendance",
                    models.ForeignKey(
                        help_text="Attendance record being audited",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="learners.workplaceattendance",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Audit Log",
                "verbose_name_plural": "Attendance Audit Logs",
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["attendance", "-changed_at"],
                        name="learners_at_attenda_24a4df_idx",
                    ),
                    models.Index(
                        fields=["action", "archived", "changed_at"],
                        name="learners_at_action_5e720f_idx",
                    ),
                    models.Index(
                        fields=["attendance", "field_changed", "-changed_at"],
                        name="learners_at_attenda_c378f3_idx",
                    ),
                ],
            },
        ),
    ]
