# Generated by Django 5.2.8 on 2025-12-31 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learners", "0008_add_attendance_audit_log"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workplaceattendance",
            name="off_site_work_verified",
            field=models.BooleanField(
                default=False,
                help_text="Mentor verified that work was performed off-site (outside geofence)",
            ),
        ),
        migrations.AddField(
            model_name="workplaceattendance",
            name="override_applied_at",
            field=models.DateTimeField(
                blank=True, help_text="When the override was applied", null=True
            ),
        ),
        migrations.AddField(
            model_name="workplaceattendance",
            name="override_applied_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who applied the override",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_overrides_applied",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workplaceattendance",
            name="override_notes",
            field=models.TextField(
                blank=True, help_text="Explanation for any manual overrides applied"
            ),
        ),
        migrations.AddField(
            model_name="workplaceattendance",
            name="time_override_clock_in",
            field=models.TimeField(
                blank=True,
                help_text="Manual override for clock-in time (if GPS timestamp incorrect)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workplaceattendance",
            name="time_override_clock_out",
            field=models.TimeField(
                blank=True,
                help_text="Manual override for clock-out time (if GPS timestamp incorrect)",
                null=True,
            ),
        ),
    ]
