# Generated by Django 5.2.8 on 2026-01-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0009_add_attendance_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='stipendcalculation',
            name='dual_verified_records',
            field=models.PositiveIntegerField(default=0, help_text='Records verified by both mentor and facilitator'),
        ),
        migrations.AddField(
            model_name='stipendcalculation',
            name='facilitator_verified_only',
            field=models.PositiveIntegerField(default=0, help_text='Records verified only by facilitator'),
        ),
        migrations.AddField(
            model_name='stipendcalculation',
            name='mentor_verified_only',
            field=models.PositiveIntegerField(default=0, help_text='Records verified only by mentor'),
        ),
        migrations.AddField(
            model_name='stipendcalculation',
            name='total_attendance_records',
            field=models.PositiveIntegerField(default=0, help_text='Total attendance records for this period'),
        ),
        migrations.AddField(
            model_name='stipendcalculation',
            name='unverified_records',
            field=models.PositiveIntegerField(default=0, help_text='Records with no verification'),
        ),
    ]
