# Generated by Django 5.2.8 on 2026-01-04 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_rename_blockplan_to_implementationplan'),
        ('corporate', '0015_hostmentor_additional_notes_hostmentor_approved_at_and_more'),
        ('learners', '0010_add_stipend_verification_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkplaceExposureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('hours_logged', models.DecimalField(decimal_places=2, help_text='Hours of exposure logged for this activity', max_digits=5)),
                ('activity_description', models.TextField(help_text='Description of the activity performed')),
                ('skills_demonstrated', models.JSONField(default=list, help_text='List of skills demonstrated during this activity')),
                ('evidence_file', models.FileField(blank=True, help_text='Photo or document evidence of the activity', null=True, upload_to='workplace_exposure/evidence/%Y/%m/')),
                ('evidence_notes', models.TextField(blank=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified by Mentor'), ('REJECTED', 'Rejected'), ('DISPUTED', 'Disputed')], default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('quality_rating', models.PositiveIntegerField(blank=True, help_text='Mentor rating 1-5 for quality of work', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplace_exposure_logs', to='academics.enrollment')),
                ('host_employer', models.ForeignKey(help_text='Host employer where exposure occurred', on_delete=django.db.models.deletion.PROTECT, related_name='exposure_logs', to='corporate.hostemployer')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_exposures', to='corporate.hostmentor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workplace_module', models.ForeignKey(help_text='Workplace module (WM) for this exposure', limit_choices_to={'module_type': 'W'}, on_delete=django.db.models.deletion.PROTECT, related_name='exposure_logs', to='academics.module')),
            ],
            options={
                'verbose_name': 'Workplace Exposure Log',
                'verbose_name_plural': 'Workplace Exposure Logs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WorkplaceRotationRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(help_text='Detailed reason for rotation recommendation')),
                ('is_system_generated', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('ACTIONED', 'Actioned'), ('DECLINED', 'Declined')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('current_host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotation_out_recommendations', to='corporate.hostemployer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_recommendations', to='academics.enrollment')),
                ('modules_needing_exposure', models.ManyToManyField(help_text='Modules where learner needs more exposure', related_name='rotation_recommendations', to='academics.module')),
                ('new_placement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotation_source', to='corporate.workplaceplacement')),
                ('recommended_host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotation_in_recommendations', to='corporate.hostemployer')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_rotations', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workplace Rotation Recommendation',
                'verbose_name_plural': 'Workplace Rotation Recommendations',
                'ordering': ['-created_at'],
            },
        ),
    ]
