# Generated by Django 5.2.8 on 2026-01-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0011_workplaceexposurelog_workplacerotationrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='signature',
            field=models.ImageField(blank=True, help_text='Digital signature PNG (400x150px, transparent background)', null=True, upload_to='signatures/learners/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='learner',
            name='signature_captured_at',
            field=models.DateTimeField(blank=True, help_text='When signature was captured', null=True),
        ),
        migrations.AddField(
            model_name='learner',
            name='signature_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash for integrity verification', max_length=64),
        ),
        migrations.AddField(
            model_name='learner',
            name='signature_locked',
            field=models.BooleanField(default=False, help_text='Signature is locked after first capture'),
        ),
    ]
