# Generated by Django 5.2.8 on 2026-01-12 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_feature_improvements'),
        ('corporate', '0019_digital_signature'),
        ('learners', '0012_digital_signature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLogbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('entry_date', models.DateField(help_text='Date of this logbook entry')),
                ('attendance_status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('SICK_LEAVE', 'Sick Leave'), ('ANNUAL_LEAVE', 'Annual Leave'), ('STUDY_LEAVE', 'Study Leave'), ('PUBLIC_HOLIDAY', 'Public Holiday'), ('LATE', 'Late Arrival'), ('EARLY_OUT', 'Early Departure')], default='PRESENT', max_length=20)),
                ('clock_in', models.TimeField(blank=True, help_text='Time arrived at workplace', null=True)),
                ('clock_out', models.TimeField(blank=True, help_text='Time left workplace', null=True)),
                ('break_minutes', models.PositiveIntegerField(default=60, help_text='Break time in minutes')),
                ('daily_summary', models.TextField(blank=True, help_text='Summary of activities for the day')),
                ('challenges_faced', models.TextField(blank=True, help_text='Any challenges or difficulties faced')),
                ('lessons_learned', models.TextField(blank=True, help_text='Key lessons learned during the day')),
                ('mentor_feedback', models.TextField(blank=True, help_text='Daily feedback from mentor if provided')),
                ('learner_signed', models.BooleanField(default=False, help_text='Learner confirmed this entry')),
                ('learner_signed_at', models.DateTimeField(blank=True, null=True)),
                ('mentor_signed', models.BooleanField(default=False, help_text='Mentor approved this entry')),
                ('mentor_signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('mentor_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_signed_daily_entries', to=settings.AUTH_USER_MODEL)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logbook_entries', to='corporate.workplaceplacement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Logbook Entry',
                'verbose_name_plural': 'Daily Logbook Entries',
                'ordering': ['-entry_date'],
                'unique_together': {('placement', 'entry_date')},
            },
        ),
        migrations.CreateModel(
            name='DailyTaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('module_code', models.CharField(blank=True, help_text='Module code (auto-filled from outcome or manual)', max_length=50)),
                ('task_description', models.TextField(help_text='Description of the task/activity performed')),
                ('hours_spent', models.DecimalField(decimal_places=2, default=1.0, help_text='Hours spent on this task', max_digits=4)),
                ('evidence_notes', models.TextField(blank=True, help_text='Notes on evidence or outputs from this task')),
                ('evidence_file', models.FileField(blank=True, help_text='Optional evidence file (photo, document)', null=True, upload_to='logbook/task_evidence/%Y/%m/')),
                ('competency_rating', models.CharField(blank=True, choices=[('NYC', 'Not Yet Competent'), ('WTC', 'Working Towards Competent'), ('C', 'Competent'), ('E', 'Exceeds Expectations')], help_text='Optional competency rating from mentor', max_length=5)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('daily_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_completions', to='learners.dailylogbookentry')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workplace_outcome', models.ForeignKey(blank=True, help_text='SAQA curriculum outcome this task relates to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_completions', to='academics.workplacemoduleoutcome')),
            ],
            options={
                'verbose_name': 'Daily Task Completion',
                'verbose_name_plural': 'Daily Task Completions',
                'ordering': ['daily_entry', 'created_at'],
            },
        ),
    ]
