# Generated by Django on 2026-01-16
# Adds attendance_record OneToOneField to DailyLogbookEntry

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0013_feature_improvements'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylogbookentry',
            name='attendance_record',
            field=models.OneToOneField(
                blank=True,
                help_text='Linked attendance record for this day',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='daily_logbook_entry',
                to='learners.workplaceattendance'
            ),
        ),
    ]
