# Generated by Django 5.2.8 on 2026-02-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0014_dailylogbookentry_attendance_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='sage_customer_id',
            field=models.CharField(blank=True, help_text='Sage Intacct Customer ID for payment integration', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('ID_COPY', 'ID Copy'), ('MATRIC', 'Matric Certificate'), ('AGREEMENT', 'Learner Agreement'), ('POE', 'Portfolio of Evidence'), ('QUALIFICATION', 'Prior Qualification'), ('EMPLOYER_LETTER', 'Employer Confirmation Letter'), ('CV', 'Curriculum Vitae'), ('PROOF_ADDRESS', 'Proof of Address'), ('BANK_CONFIRM', 'Bank Confirmation'), ('PROOF_OF_PAYMENT', 'Proof of Payment'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
