# Generated by Django 5.2.8 on 2026-02-17 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0015_learner_sage_customer_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('notify_assessment_completed', models.BooleanField(default=True, help_text='Email when learner completes an assessment')),
                ('notify_assessment_scheduled', models.BooleanField(default=True, help_text='Email when new assessments are scheduled')),
                ('notify_schedule_changed', models.BooleanField(default=True, help_text='Email when assessment schedule changes')),
                ('notify_weekly_progress', models.BooleanField(default=False, help_text='Weekly progress summary email')),
                ('notify_monthly_report', models.BooleanField(default=True, help_text='Monthly progress report email')),
                ('notify_absence', models.BooleanField(default=True, help_text='Email when learner is marked absent')),
                ('notify_not_yet_competent', models.BooleanField(default=True, help_text='Email when learner receives NYC result')),
                ('notify_competent', models.BooleanField(default=True, help_text='Email when learner achieves competence')),
                ('notify_module_completed', models.BooleanField(default=True, help_text='Email when learner completes a module')),
                ('preferred_language', models.CharField(default='en', max_length=5)),
                ('email_frequency', models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('DAILY_DIGEST', 'Daily Digest'), ('WEEKLY_DIGEST', 'Weekly Digest')], default='IMMEDIATE', max_length=20)),
                ('unsubscribed', models.BooleanField(default=False)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('guardian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='learners.guardian')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guardian Notification Preference',
                'verbose_name_plural': 'Guardian Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='GuardianPortalAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('access_code', models.CharField(max_length=20, unique=True)),
                ('access_code_expires', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('login_count', models.PositiveIntegerField(default=0)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('guardian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_access', to='learners.guardian')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guardian Portal Access',
                'verbose_name_plural': 'Guardian Portal Accesses',
            },
        ),
    ]
