# Generated by Django 5.2.8 on 2026-01-26 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_add_phase_type_choices'),
        ('crm', '0001_initial'),
        ('learners', '0014_dailylogbookentry_attendance_record'),
        ('tenants', '0002_extend_campus_code_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='consent_bulk_messaging',
            field=models.BooleanField(default=False, help_text='Consent to receive monthly bulk messages'),
        ),
        migrations.AddField(
            model_name='lead',
            name='consent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='For school leavers - track age progression', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='expected_matric_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='grade',
            field=models.CharField(blank=True, help_text='e.g., Grade 11, Grade 12, Matric', max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('SCHOOL_LEAVER', 'School Leaver'), ('ADULT', 'Adult Learner'), ('CORPORATE', 'Corporate/Employer'), ('REFERRAL', 'Referral')], default='ADULT', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='lead',
            name='parent_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='parent_relationship',
            field=models.CharField(blank=True, help_text='e.g., Mother, Father, Guardian', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='school_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='unsubscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='unsubscribed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['lead_type', 'status'], name='crm_lead_lead_ty_9c5ba1_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['date_of_birth'], name='crm_lead_date_of_cb079c_idx'),
        ),
    ]
