# Generated by Django 5.2.8 on 2026-02-05 07:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_migrate_yearly_pricing'),
        ('crm', '0003_alter_leadactivity_activity_type_application_and_more'),
        ('learners', '0014_dailylogbookentry_attendance_record'),
        ('tenants', '0002_extend_campus_code_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StageBlueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_actions', models.JSONField(blank=True, default=list, help_text="List of recommended actions: [{'action': 'Call lead', 'description': '...'}]")),
                ('auto_tasks', models.JSONField(blank=True, default=list, help_text="Tasks to auto-create: [{'title': 'Send welcome email', 'due_days': 1}]")),
                ('notify_agent_on_entry', models.BooleanField(default=True)),
                ('notify_agent_on_overdue', models.BooleanField(default=True)),
                ('overdue_notification_days', models.PositiveIntegerField(default=3, help_text='Days after expected duration to send overdue notification')),
                ('auto_send_initial_communication', models.BooleanField(default=False, help_text='Automatically send initial communication when lead enters stage')),
                ('auto_schedule_follow_up', models.BooleanField(default=True, help_text='Automatically schedule next communication based on frequency')),
            ],
            options={
                'verbose_name': 'Stage Blueprint',
                'verbose_name_plural': 'Stage Blueprints',
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='engagement_score',
            field=models.IntegerField(default=0, help_text='Calculated score based on client interactions'),
        ),
        migrations.AddField(
            model_name='lead',
            name='fallback_contact_methods',
            field=models.JSONField(blank=True, default=list, help_text="Ordered list of fallback contact methods: ['EMAIL', 'SMS']"),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_engagement_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last client engagement event', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_scheduled_communication',
            field=models.DateTimeField(blank=True, help_text='Next scheduled automated communication', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='nurture_active',
            field=models.BooleanField(default=True, help_text='Whether automated communications are active for this lead'),
        ),
        migrations.AddField(
            model_name='lead',
            name='preferred_contact_method',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('PHONE', 'Phone Call')], default='WHATSAPP', help_text='Primary contact method for automated communications', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='stage_entered_at',
            field=models.DateTimeField(blank=True, help_text='When lead entered current stage', null=True),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='automation_source',
            field=models.CharField(blank=True, help_text="e.g., 'nurture_cycle', 'stage_blueprint'", max_length=100),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='is_automated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='activity_type',
            field=models.CharField(choices=[('CALL', 'Phone Call'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS'), ('MEETING', 'Meeting'), ('NOTE', 'Note'), ('STATUS_CHANGE', 'Status Change'), ('STAGE_CHANGE', 'Pipeline Stage Change'), ('ASSIGNMENT', 'Assignment'), ('FOLLOW_UP', 'Follow-up Scheduled'), ('DOCUMENT', 'Document'), ('QUOTE_SENT', 'Quote Sent'), ('QUOTE_VIEWED', 'Quote Viewed'), ('QUOTE_ACCEPTED', 'Quote Accepted'), ('COMMUNICATION_SENT', 'Automated Communication Sent')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='from_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='to_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='CommunicationCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('frequency_days', models.PositiveIntegerField(help_text='Days until next communication')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('channel_used', models.CharField(blank=True, help_text='WHATSAPP, EMAIL, SMS', max_length=20)),
                ('message_id', models.CharField(blank=True, help_text='Reference to sent message', max_length=200)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('pause_reason', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_cycles', to='crm.lead')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_communications', to='crm.messagetemplate')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Communication Cycle',
                'verbose_name_plural': 'Communication Cycles',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('QUOTE_VIEWED', 'Quote Viewed'), ('QUOTE_ACCEPTED', 'Quote Accepted'), ('QUOTE_REJECTED', 'Quote Rejected'), ('EMAIL_OPENED', 'Email Opened'), ('EMAIL_CLICKED', 'Email Link Clicked'), ('WHATSAPP_READ', 'WhatsApp Read'), ('WEBSITE_VISIT', 'Website Visit'), ('FORM_SUBMITTED', 'Form Submitted'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('CALL_ANSWERED', 'Call Answered'), ('CALL_MISSED', 'Call Missed'), ('MEETING_ATTENDED', 'Meeting Attended'), ('MEETING_MISSED', 'Meeting Missed')], max_length=30)),
                ('event_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event data: {quote_id, email_id, page_url, etc.}')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('score_value', models.IntegerField(default=0)),
                ('agent_notified', models.BooleanField(default=False)),
                ('agent_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='crm.lead')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead Engagement',
                'verbose_name_plural': 'Lead Engagements',
                'ordering': ['-event_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AgentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('notification_type', models.CharField(choices=[('ENGAGEMENT', 'Client Engagement'), ('STAGE_CHANGE', 'Stage Change'), ('NEW_LEAD', 'New Lead Assigned'), ('LEAD_OVERDUE', 'Lead Overdue'), ('FOLLOW_UP_DUE', 'Follow-up Due'), ('QUOTE_ACTIVITY', 'Quote Activity'), ('COMMUNICATION_SCHEDULED', 'Communication Scheduled'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_OVERDUE', 'Task Overdue'), ('SYSTEM', 'System Notification')], max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('action_label', models.CharField(blank=True, max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_notifications', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_notifications', to='crm.lead')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='crm.leadengagement')),
            ],
            options={
                'verbose_name': 'Agent Notification',
                'verbose_name_plural': 'Agent Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('learner_type', models.CharField(choices=[('SCHOOL_LEAVER_FUTURE', 'School Leaver - Future (Gr9-11)'), ('SCHOOL_LEAVER_READY', 'School Leaver - Ready Now (Gr12/Matric)'), ('ADULT', 'Adult Learner'), ('CORPORATE', 'Corporate/Employer Referral'), ('REFERRAL', 'General Referral')], max_length=30)),
                ('default_communication_frequency_days', models.PositiveIntegerField(choices=[(7, 'Weekly'), (14, 'Bi-weekly'), (30, 'Monthly'), (90, 'Quarterly'), (180, 'Bi-annually'), (365, 'Annually')], default=14, help_text='Default days between automated communications')),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('icon', models.CharField(default='fa-user-graduate', max_length=50)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='tenants.campus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pipeline',
                'verbose_name_plural': 'Pipelines',
                'ordering': ['campus', 'learner_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='pipeline',
            field=models.ForeignKey(blank=True, help_text='The pipeline this lead is in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.pipeline'),
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Internal code for stage', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('expected_duration_days', models.PositiveIntegerField(default=7, help_text='Expected time a lead should spend in this stage')),
                ('communication_frequency_days', models.PositiveIntegerField(blank=True, help_text="Override pipeline's default communication frequency for this stage", null=True)),
                ('is_entry_stage', models.BooleanField(default=False, help_text='New leads start here')),
                ('is_won_stage', models.BooleanField(default=False, help_text='Indicates successful conversion')),
                ('is_lost_stage', models.BooleanField(default=False, help_text='Indicates lost lead')),
                ('is_nurture_stage', models.BooleanField(default=False, help_text='Long-term nurture (e.g., future learners)')),
                ('color', models.CharField(default='#6B7280', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('win_probability', models.PositiveIntegerField(default=0, help_text='Likelihood of conversion at this stage (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='crm.pipeline')),
            ],
            options={
                'verbose_name': 'Pipeline Stage',
                'verbose_name_plural': 'Pipeline Stages',
                'ordering': ['pipeline', 'order'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='current_stage',
            field=models.ForeignKey(blank=True, help_text='Current stage within the pipeline', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.pipelinestage'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['pipeline', 'current_stage'], name='crm_lead_pipelin_fa8b63_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['engagement_score'], name='crm_lead_engagem_3d469a_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['next_scheduled_communication'], name='crm_lead_next_sc_bb1835_idx'),
        ),
        migrations.AddField(
            model_name='stageblueprint',
            name='communication_templates',
            field=models.ManyToManyField(blank=True, help_text='Message templates for automated communications', related_name='stage_blueprints', to='crm.messagetemplate'),
        ),
        migrations.AddField(
            model_name='stageblueprint',
            name='default_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_stages', to='crm.messagetemplate'),
        ),
        migrations.AddField(
            model_name='stageblueprint',
            name='stage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blueprint', to='crm.pipelinestage'),
        ),
        migrations.AddIndex(
            model_name='communicationcycle',
            index=models.Index(fields=['status', 'scheduled_at'], name='crm_communi_status_3a5b9c_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationcycle',
            index=models.Index(fields=['lead', 'is_active'], name='crm_communi_lead_id_3cfba7_idx'),
        ),
        migrations.AddIndex(
            model_name='leadengagement',
            index=models.Index(fields=['lead', 'event_type'], name='crm_leadeng_lead_id_e89eef_idx'),
        ),
        migrations.AddIndex(
            model_name='leadengagement',
            index=models.Index(fields=['event_timestamp'], name='crm_leadeng_event_t_5997a4_idx'),
        ),
        migrations.AddIndex(
            model_name='agentnotification',
            index=models.Index(fields=['agent', 'is_read'], name='crm_agentno_agent_i_283b22_idx'),
        ),
        migrations.AddIndex(
            model_name='agentnotification',
            index=models.Index(fields=['agent', 'notification_type'], name='crm_agentno_agent_i_e403a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pipelinestage',
            unique_together={('pipeline', 'code')},
        ),
    ]
