# Generated by Django 5.2.8 on 2026-02-05 09:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_migrate_yearly_pricing'),
        ('crm', '0004_pipeline_nurture_system'),
        ('intakes', '0003_contract_and_learner_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address (at least one contact method required)', max_length=254),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number (at least one contact method required)', max_length=20),
        ),
        migrations.CreateModel(
            name='PreApprovalLetter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('letter_number', models.CharField(help_text='PAL-2026-00001', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('VIEWED', 'Viewed'), ('ACCEPTED', 'Accepted - Started Application'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='DRAFT', max_length=20)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('valid_until', models.DateField(help_text='Pre-approval expiry date')),
                ('entry_requirements_confirmed', models.BooleanField(default=False, help_text='Sales agent confirmed learner meets/will meet entry requirements')),
                ('entry_requirements_notes', models.TextField(blank=True, help_text='Notes on how entry requirements will be met')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_via', models.CharField(blank=True, help_text='EMAIL, WHATSAPP, etc.', max_length=20)),
                ('sent_to_contact', models.CharField(blank=True, help_text='Email/phone sent to', max_length=200)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pre_approval_letters/')),
                ('confirmation_notes', models.TextField(blank=True, help_text='Agent notes on why pre-approved')),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_approval_letter', to='crm.application')),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_approvals_confirmed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('intake', models.ForeignKey(blank=True, help_text='Specific intake if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_approval_letters', to='intakes.intake')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_approval_letters', to='crm.lead')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pre_approval_letters', to='academics.qualification')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pre-Approval Letter',
                'verbose_name_plural': 'Pre-Approval Letters',
                'ordering': ['-issued_date'],
            },
        ),
    ]
