# Generated by Django 5.2.8 on 2026-02-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_preapproval_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='preapprovalletter',
            name='learner_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preapprovalletter',
            name='learner_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preapprovalletter',
            name='learner_accepted_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preapprovalletter',
            name='learner_accepted_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preapprovalletter',
            name='parent_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preapprovalletter',
            name='parent_consent_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preapprovalletter',
            name='parent_consent_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preapprovalletter',
            name='parent_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preapprovalletter',
            name='parent_sent_to',
            field=models.CharField(blank=True, help_text='Parent email/phone sent to', max_length=200),
        ),
    ]
