# Generated by Django 5.2.8 on 2026-02-10 12:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_add_campuses_to_personnel'),
        ('crm', '0008_add_card_scan_source'),
        ('tenants', '0002_extend_campus_code_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebFormSource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Friendly name (e.g., 'Main College Website')", max_length=100)),
                ('domain', models.CharField(help_text="Website domain (e.g., 'collegename.co.za')", max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('webhook_secret', models.CharField(blank=True, help_text='Secret key for webhook verification (sent in X-Webhook-Secret header)', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('total_leads_created', models.PositiveIntegerField(default=0)),
                ('total_duplicates_updated', models.PositiveIntegerField(default=0)),
                ('last_submission_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_form_sources', to='tenants.brand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('default_campus', models.ForeignKey(blank=True, help_text="Default campus if form doesn't specify one", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_web_form_sources', to='tenants.campus')),
                ('default_lead_source', models.ForeignKey(blank=True, help_text='Default lead source for this website', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.leadsource')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Web Form Source',
                'verbose_name_plural': 'Web Form Sources',
                'ordering': ['brand', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WebFormMapping',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form_id', models.CharField(help_text='Gravity Forms ID or other form identifier', max_length=50)),
                ('form_name', models.CharField(help_text='Descriptive name for this form', max_length=200)),
                ('lead_type', models.CharField(choices=[('SCHOOL_LEAVER', 'School Leaver'), ('ADULT', 'Adult Learner'), ('CORPORATE', 'Corporate/Employer'), ('REFERRAL', 'Referral')], default='ADULT', help_text='Lead type for leads from this form', max_length=20)),
                ('field_mapping', models.JSONField(default=dict, help_text='Maps form field IDs to Lead model fields')),
                ('default_values', models.JSONField(blank=True, default=dict, help_text="Default values for Lead fields (e.g., {'lead_type': 'SCHOOL_LEAVER'})")),
                ('is_active', models.BooleanField(default=True)),
                ('leads_created', models.PositiveIntegerField(default=0)),
                ('duplicates_updated', models.PositiveIntegerField(default=0)),
                ('last_submission_at', models.DateTimeField(blank=True, null=True)),
                ('auto_assign_to', models.ForeignKey(blank=True, help_text='Automatically assign leads from this form to this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webform_auto_assignments', to=settings.AUTH_USER_MODEL)),
                ('campus', models.ForeignKey(blank=True, help_text='Campus for leads from this form (overrides source default)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_form_mappings', to='tenants.campus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('pipeline', models.ForeignKey(blank=True, help_text='Pipeline to assign leads to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.pipeline')),
                ('qualification', models.ForeignKey(blank=True, help_text='Default qualification interest for this form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_form_mappings', to='academics.qualification')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_mappings', to='crm.webformsource')),
            ],
            options={
                'verbose_name': 'Web Form Mapping',
                'verbose_name_plural': 'Web Form Mappings',
                'ordering': ['source', 'form_name'],
                'unique_together': {('source', 'form_id')},
            },
        ),
        migrations.CreateModel(
            name='WebFormSubmission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_payload', models.JSONField(help_text='Original webhook payload')),
                ('mapped_data', models.JSONField(default=dict, help_text='Data after field mapping applied')),
                ('status', models.CharField(choices=[('SUCCESS', 'Lead Created'), ('DUPLICATE', 'Duplicate Updated'), ('FAILED', 'Failed'), ('IGNORED', 'Ignored')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('form_mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='crm.webformmapping')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_form_submissions', to='crm.lead')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='crm.webformsource')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Web Form Submission',
                'verbose_name_plural': 'Web Form Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
