# Generated by Django 5.2.8 on 2026-02-16 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_leaddocument_document_type_educationhistory_and_more'),
        ('learners', '0015_learner_sage_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='disability_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='english_reading',
            field=models.CharField(blank=True, choices=[('POOR', 'Poor'), ('GOOD', 'Good'), ('EXCELLENT', 'Excellent')], max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='english_speaking',
            field=models.CharField(blank=True, choices=[('POOR', 'Poor'), ('GOOD', 'Good'), ('EXCELLENT', 'Excellent')], max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='english_writing',
            field=models.CharField(blank=True, choices=[('POOR', 'Poor'), ('GOOD', 'Good'), ('EXCELLENT', 'Excellent')], max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='first_language',
            field=models.CharField(blank=True, choices=[('ENGLISH', 'English'), ('AFRIKAANS', 'Afrikaans'), ('ZULU', 'isiZulu'), ('XHOSA', 'isiXhosa'), ('SOTHO', 'Sesotho'), ('TSWANA', 'Setswana'), ('PEDI', 'Sepedi'), ('VENDA', 'Tshivenda'), ('TSONGA', 'Xitsonga'), ('SWATI', 'siSwati'), ('NDEBELE', 'isiNdebele'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AddField(
            model_name='lead',
            name='has_disability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='has_medical_conditions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='highest_grade_passed',
            field=models.CharField(blank=True, choices=[('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12 / Matric')], max_length=2),
        ),
        migrations.AddField(
            model_name='lead',
            name='id_number',
            field=models.CharField(blank=True, help_text='SA ID Number (13 digits)', max_length=13),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_school_attended',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Allergies, Epilepsy, etc.'),
        ),
        migrations.AddField(
            model_name='lead',
            name='number_of_dependents',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='payment_responsibility',
            field=models.CharField(blank=True, choices=[('SELF', 'Self'), ('EMPLOYER', 'Employer'), ('SPONSOR', 'Sponsor/Family'), ('BURSARY', 'Bursary/SETA'), ('NSFAS', 'NSFAS'), ('LOAN', 'Student Loan')], max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='physical_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_physical', to='learners.address'),
        ),
        migrations.AddField(
            model_name='lead',
            name='postal_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_postal', to='learners.address'),
        ),
        migrations.AddField(
            model_name='lead',
            name='postal_same_as_physical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='race',
            field=models.CharField(blank=True, choices=[('B', 'Black'), ('W', 'White'), ('C', 'Coloured'), ('I', 'Indian/Asian'), ('O', 'Other')], max_length=1),
        ),
        migrations.AddField(
            model_name='lead',
            name='second_language',
            field=models.CharField(blank=True, choices=[('ENGLISH', 'English'), ('AFRIKAANS', 'Afrikaans'), ('ZULU', 'isiZulu'), ('XHOSA', 'isiXhosa'), ('SOTHO', 'Sesotho'), ('TSWANA', 'Setswana'), ('PEDI', 'Sepedi'), ('VENDA', 'Tshivenda'), ('TSONGA', 'Xitsonga'), ('SWATI', 'siSwati'), ('NDEBELE', 'isiNdebele'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='subjects_completed',
            field=models.TextField(blank=True, help_text='List of subjects completed'),
        ),
        migrations.AddField(
            model_name='lead',
            name='tertiary_qualification',
            field=models.CharField(blank=True, help_text='Tertiary or other qualification', max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='title',
            field=models.CharField(blank=True, choices=[('MR', 'Mr'), ('MS', 'Ms'), ('MRS', 'Mrs'), ('DR', 'Dr'), ('PROF', 'Prof')], max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='work_status',
            field=models.CharField(blank=True, choices=[('EMPLOYED', 'Employed'), ('UNEMPLOYED', 'Unemployed'), ('STUDENT', 'Student'), ('SELF_EMPLOYED', 'Self-Employed')], max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='years_experience',
            field=models.PositiveIntegerField(blank=True, help_text='Years of work experience', null=True),
        ),
        migrations.AddField(
            model_name='secondarycontact',
            name='company_vat_number',
            field=models.CharField(blank=True, help_text='Company VAT number', max_length=50),
        ),
        migrations.AlterField(
            model_name='secondarycontact',
            name='relationship',
            field=models.CharField(choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('SPOUSE', 'Spouse'), ('EMPLOYER', 'Employer'), ('GIRLFRIEND', 'Girlfriend'), ('BOYFRIEND', 'Boyfriend'), ('GUARDIAN', 'Guardian'), ('SIBLING', 'Sibling'), ('NEXT_OF_KIN', 'Next of Kin'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
