# Generated by Django 5.2.8 on 2026-02-16 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_add_campuses_to_personnel'),
        ('crm', '0013_lead_disability_description_lead_english_reading_and_more'),
        ('learners', '0015_learner_sage_customer_id_and_more'),
        ('tenants', '0004_add_campus_capacity_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadPipelineMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('EXITED', 'Exited')], default='ACTIVE', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('stage_entered_at', models.DateTimeField(blank=True, null=True)),
                ('last_stage_change', models.DateTimeField(blank=True, null=True)),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('next_communication_at', models.DateTimeField(blank=True, null=True)),
                ('last_communication_at', models.DateTimeField(blank=True, null=True)),
                ('communications_paused', models.BooleanField(default=False)),
                ('pause_reason', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Lead Pipeline Membership',
                'verbose_name_plural': 'Lead Pipeline Memberships',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='created_from_pre_approval',
            field=models.ForeignKey(blank=True, help_text='The pre-approval letter that triggered this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spawned_applications', to='crm.preapprovalletter'),
        ),
        migrations.AddField(
            model_name='application',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Application is archived once learner starts studying'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='auto_create_application_on_ready',
            field=models.BooleanField(default=False, help_text='Automatically create application when lead meets eligibility criteria'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='min_age_for_application',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum age in years for application eligibility', null=True),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='min_grade_for_application',
            field=models.CharField(blank=True, help_text="Minimum grade for application eligibility (e.g., 'GRADE_12', 'GRADE_11')", max_length=20),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='requires_pre_approval',
            field=models.BooleanField(default=False, help_text='If True, pre-approval letter required before application can be created'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['is_archived', 'status'], name='crm_applica_is_arch_fc6ade_idx'),
        ),
        migrations.AddField(
            model_name='leadpipelinemembership',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadpipelinemembership',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='crm.pipelinestage'),
        ),
        migrations.AddField(
            model_name='leadpipelinemembership',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadpipelinemembership',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_memberships', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='leadpipelinemembership',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='crm.pipeline'),
        ),
        migrations.AddField(
            model_name='leadpipelinemembership',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='leadpipelinemembership',
            index=models.Index(fields=['status', 'next_communication_at'], name='crm_leadpip_status_58360e_idx'),
        ),
        migrations.AddIndex(
            model_name='leadpipelinemembership',
            index=models.Index(fields=['lead', 'status'], name='crm_leadpip_lead_id_93e2cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leadpipelinemembership',
            unique_together={('lead', 'pipeline')},
        ),
    ]
