# Generated by Django 5.2.8 on 2026-02-16 20:33

from django.db import migrations
from django.utils import timezone


def migrate_lead_pipelines_to_memberships(apps, schema_editor):
    """
    Migrate existing Lead.pipeline FK values to LeadPipelineMembership records.
    This allows leads to be in multiple pipelines while preserving existing data.
    """
    Lead = apps.get_model('crm', 'Lead')
    LeadPipelineMembership = apps.get_model('crm', 'LeadPipelineMembership')
    
    # Get all leads that have a pipeline assigned
    leads_with_pipeline = Lead.objects.filter(pipeline__isnull=False)
    
    memberships_created = 0
    for lead in leads_with_pipeline:
        # Check if membership already exists (shouldn't, but safety check)
        existing = LeadPipelineMembership.objects.filter(
            lead=lead,
            pipeline=lead.pipeline
        ).exists()
        
        if not existing:
            LeadPipelineMembership.objects.create(
                lead=lead,
                pipeline=lead.pipeline,
                current_stage=lead.current_stage,
                status='ACTIVE',
                stage_entered_at=lead.stage_entered_at,
                # Auto-set timestamps
                created_at=lead.created_at or timezone.now(),
                updated_at=timezone.now(),
            )
            memberships_created += 1
    
    print(f"Created {memberships_created} LeadPipelineMembership records from existing Lead.pipeline data")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - delete all memberships (the Lead.pipeline FK still exists).
    """
    LeadPipelineMembership = apps.get_model('crm', 'LeadPipelineMembership')
    LeadPipelineMembership.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_add_pipeline_membership_and_application_archiving'),
    ]

    operations = [
        migrations.RunPython(
            migrate_lead_pipelines_to_memberships,
            reverse_code=reverse_migration
        ),
    ]
