# Generated by Django 5.2.8 on 2026-02-16 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_migrate_lead_pipelines_to_memberships'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='merged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='merged_by',
            field=models.ForeignKey(blank=True, help_text='User who performed the merge', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='merged_into',
            field=models.ForeignKey(blank=True, help_text='If this lead was merged, points to the primary lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_duplicates', to='crm.lead'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New Inquiry'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('PROPOSAL', 'Proposal Sent'), ('NEGOTIATION', 'Negotiation'), ('REGISTERED', 'Registered'), ('ENROLLED', 'Enrolled'), ('LOST', 'Lost'), ('ALUMNI', 'Alumni'), ('MERGED', 'Merged Duplicate')], default='NEW', max_length=20),
        ),
    ]
