# Generated by Django 5.2.8 on 2026-01-21 18:05

import integrations.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_alter_integrationconnection_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationconnection',
            name='api_key',
            field=integrations.encryption.EncryptedCharField(blank=True, help_text='API Key or Token', max_length=1000),
        ),
        migrations.AlterField(
            model_name='integrationconnection',
            name='api_secret',
            field=integrations.encryption.EncryptedCharField(blank=True, help_text='API Secret', max_length=1000),
        ),
        migrations.AlterField(
            model_name='integrationconnection',
            name='client_id',
            field=integrations.encryption.EncryptedCharField(blank=True, help_text='OAuth Client ID', max_length=1000),
        ),
        migrations.AlterField(
            model_name='integrationconnection',
            name='client_secret',
            field=integrations.encryption.EncryptedCharField(blank=True, help_text='OAuth Client Secret', max_length=1000),
        ),
        migrations.AlterField(
            model_name='integrationwebhook',
            name='secret_key',
            field=integrations.encryption.EncryptedCharField(help_text='HMAC secret for signature verification', max_length=1000),
        ),
    ]
