# Generated by Django 5.2.8 on 2025-11-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment_number', models.CharField(max_length=30, unique=True)),
                ('application_date', models.DateField()),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_completion', models.DateField()),
                ('actual_completion', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('DOC_CHECK', 'Document Check'), ('REGISTERED', 'Registered'), ('ENROLLED', 'Enrolled'), ('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CERTIFIED', 'Certified'), ('WITHDRAWN', 'Withdrawn'), ('TRANSFERRED', 'Transferred'), ('EXPIRED', 'Expired')], default='APPLIED', max_length=20)),
                ('status_reason', models.TextField(blank=True)),
                ('status_changed_at', models.DateTimeField(auto_now=True)),
                ('funding_type', models.CharField(choices=[('SELF', 'Self-funded'), ('EMPLOYER', 'Employer-funded'), ('BURSARY', 'Bursary'), ('LEARNERSHIP', 'Learnership'), ('INTERNSHIP', 'Internship'), ('SKILLS_PROG', 'Skills Programme'), ('DISCRETIONARY', 'Discretionary Grant'), ('PIVOTAL', 'PIVOTAL Grant')], default='SELF', max_length=20)),
                ('funding_source', models.CharField(blank=True, max_length=100)),
                ('funding_reference', models.CharField(blank=True, max_length=50)),
                ('agreement_signed', models.BooleanField(default=False)),
                ('agreement_date', models.DateField(blank=True, null=True)),
                ('nlrd_submitted', models.BooleanField(default=False)),
                ('nlrd_submission_date', models.DateField(blank=True, null=True)),
                ('nlrd_reference', models.CharField(blank=True, max_length=50)),
                ('certificate_number', models.CharField(blank=True, max_length=50)),
                ('certificate_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Enrollment Status History',
                'verbose_name_plural': 'Enrollment Status Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('module_type', models.CharField(choices=[('K', 'Knowledge'), ('P', 'Practical'), ('W', 'Workplace')], max_length=1)),
                ('credits', models.PositiveIntegerField()),
                ('notional_hours', models.PositiveIntegerField()),
                ('sequence_order', models.PositiveIntegerField(default=1)),
                ('is_compulsory', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['qualification', 'sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='ModuleUnitStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Module Unit Standard',
                'verbose_name_plural': 'Module Unit Standards',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('saqa_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('short_title', models.CharField(max_length=100)),
                ('nqf_level', models.PositiveIntegerField()),
                ('credits', models.PositiveIntegerField()),
                ('qualification_type', models.CharField(choices=[('OC', 'Occupational Certificate'), ('NC', 'National Certificate'), ('ND', 'National Diploma'), ('PQ', 'Part Qualification'), ('SP', 'Skills Programme'), ('LP', 'Learnership Programme')], max_length=5)),
                ('minimum_duration_months', models.PositiveIntegerField(default=12)),
                ('maximum_duration_months', models.PositiveIntegerField(default=36)),
                ('registration_start', models.DateField()),
                ('registration_end', models.DateField()),
                ('last_enrollment_date', models.DateField()),
                ('accreditation_number', models.CharField(blank=True, max_length=50)),
                ('accreditation_expiry', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UnitStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saqa_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('nqf_level', models.PositiveIntegerField()),
                ('credits', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unit Standard',
                'verbose_name_plural': 'Unit Standards',
                'ordering': ['saqa_id'],
            },
        ),
    ]
