# Generated by Django 5.2.8 on 2025-12-06 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_initial"),
        ("learners", "0002_wbl_models"),
        ("tenants", "0002_extend_campus_code_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="qualification",
            name="accreditation_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="qualifications/accreditation/%Y/"
            ),
        ),
        migrations.AddField(
            model_name="qualification",
            name="accreditation_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="qualification",
            name="delivery_notes",
            field=models.TextField(
                blank=True, help_text="Notes on delivery readiness status"
            ),
        ),
        migrations.AddField(
            model_name="qualification",
            name="qcto_code",
            field=models.CharField(
                blank=True, help_text="QCTO-specific qualification code", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="qualification",
            name="ready_hybrid",
            field=models.BooleanField(
                default=False, help_text="Ready for hybrid/blended delivery"
            ),
        ),
        migrations.AddField(
            model_name="qualification",
            name="ready_in_person",
            field=models.BooleanField(
                default=False, help_text="Ready for in-person/contact delivery"
            ),
        ),
        migrations.AddField(
            model_name="qualification",
            name="ready_online",
            field=models.BooleanField(
                default=False, help_text="Ready for online/distance delivery"
            ),
        ),
        migrations.CreateModel(
            name="AccreditationChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("DOCUMENTATION", "Documentation"),
                            ("PERSONNEL", "Personnel & Staffing"),
                            ("FACILITIES", "Facilities & Equipment"),
                            ("MATERIALS", "Learning Materials"),
                            ("COMPLIANCE", "Compliance & Policies"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                ("sequence_order", models.PositiveIntegerField(default=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "qualification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="academics.qualification",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Accreditation Checklist Item",
                "verbose_name_plural": "Accreditation Checklist Items",
                "ordering": ["qualification", "category", "sequence_order"],
            },
        ),
        migrations.CreateModel(
            name="AccreditationChecklistProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "checklist_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="academics.accreditationchecklistitem",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_checklist_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evidence_documents",
                    models.ManyToManyField(
                        blank=True,
                        related_name="checklist_evidence",
                        to="learners.document",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Accreditation Checklist Progress",
                "verbose_name_plural": "Accreditation Checklist Progress",
                "ordering": ["-completed_at"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("OHS_POLICY", "OHS Policy"),
                            ("FIRE_CERT", "Fire Safety Certificate"),
                            ("FIRST_AID", "First Aid Certificate"),
                            ("EVACUATION_PLAN", "Evacuation Plan"),
                            ("SETA_LETTER", "SETA Accreditation Letter"),
                            ("ACCREDITATION", "Accreditation Certificate"),
                            ("INSURANCE", "Insurance Certificate"),
                            ("BUSINESS_LICENSE", "Business License"),
                            ("LEASE_AGREEMENT", "Lease Agreement"),
                            ("EQUIPMENT_CERT", "Equipment Certification"),
                            ("OTHER", "Other Compliance Document"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("file", models.FileField(upload_to="compliance/%Y/%m/")),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "reminder_days",
                    models.PositiveIntegerField(
                        default=180, help_text="Days before expiry to trigger reminder"
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campus",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for organisation-wide documents",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_documents",
                        to="tenants.campus",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_compliance_docs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Compliance Document",
                "verbose_name_plural": "Compliance Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AccreditationAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("6_MONTHS", "6 Months Notice"),
                            ("3_MONTHS", "3 Months Notice"),
                            ("1_MONTH", "1 Month Notice"),
                            ("EXPIRED", "Expired"),
                        ],
                        max_length=20,
                    ),
                ),
                ("alert_date", models.DateField()),
                ("message", models.TextField()),
                ("acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("action_taken", models.TextField(blank=True)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "qualification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accreditation_alerts",
                        to="academics.qualification",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "compliance_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_alerts",
                        to="academics.compliancedocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accreditation Alert",
                "verbose_name_plural": "Accreditation Alerts",
                "ordering": ["alert_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LearningMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("LEARNER_GUIDE", "Learner Guide"),
                            ("FACILITATOR_GUIDE", "Facilitator Guide"),
                            ("ASSESSMENT_PACK", "Assessment Pack"),
                            ("POE_GUIDE", "Portfolio of Evidence Guide"),
                            ("WORKBOOK", "Workbook"),
                            ("PRESENTATION", "Presentation Slides"),
                            ("VIDEO", "Video Content"),
                            ("OTHER", "Other Material"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="learning_materials/%Y/"
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True, help_text="Link to LMS or external resource"
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("last_reviewed", models.DateField(blank=True, null=True)),
                ("next_review_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=True)),
                ("approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_materials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "qualification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_materials",
                        to="academics.qualification",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Learning Material",
                "verbose_name_plural": "Learning Materials",
                "ordering": ["qualification", "material_type", "-version"],
            },
        ),
        migrations.CreateModel(
            name="PersonnelRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "personnel_type",
                    models.CharField(
                        choices=[
                            ("FACILITATOR", "Facilitator"),
                            ("ASSESSOR", "Assessor"),
                            ("MODERATOR", "Moderator"),
                            (
                                "SKILLS_DEV_FACILITATOR",
                                "Skills Development Facilitator",
                            ),
                        ],
                        max_length=30,
                    ),
                ),
                ("registration_number", models.CharField(max_length=50)),
                ("registration_date", models.DateField()),
                ("expiry_date", models.DateField()),
                (
                    "certificate",
                    models.FileField(
                        blank=True, null=True, upload_to="personnel/registrations/%Y/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "qualifications",
                    models.ManyToManyField(
                        blank=True,
                        related_name="registered_personnel",
                        to="academics.qualification",
                    ),
                ),
                (
                    "seta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="personnel_registrations",
                        to="learners.seta",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personnel_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Personnel Registration",
                "verbose_name_plural": "Personnel Registrations",
                "ordering": ["user", "-registration_date"],
            },
        ),
        migrations.CreateModel(
            name="QualificationCampusAccreditation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("accredited_from", models.DateField()),
                ("accredited_until", models.DateField()),
                (
                    "learner_capacity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of learners this campus can enroll",
                        null=True,
                    ),
                ),
                (
                    "accreditation_reference",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "accreditation_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="qualifications/campus_accreditation/%Y/",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualification_accreditations",
                        to="tenants.campus",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "qualification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campus_accreditations",
                        to="academics.qualification",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Campus Accreditation",
                "verbose_name_plural": "Campus Accreditations",
                "ordering": ["qualification", "campus"],
                "unique_together": {("qualification", "campus")},
            },
        ),
    ]
