# Generated by Django 5.2.8 on 2025-12-08 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_qualification_accreditation_certificate_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="module",
            options={"ordering": ["qualification", "year_level", "sequence_order"]},
        ),
        migrations.AddField(
            model_name="module",
            name="component_phase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INSTITUTIONAL", "Institutional"),
                    ("WORKPLACE", "Workplace"),
                ],
                help_text="Auto-set based on module type: K/P = Institutional, W = Workplace",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="year_level",
            field=models.PositiveIntegerField(
                choices=[(1, "Year 1"), (2, "Year 2"), (3, "Year 3")],
                default=1,
                help_text="Which year of study this module belongs to",
            ),
        ),
        migrations.CreateModel(
            name="LearnerModuleProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "formative_status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPETENT", "Competent"),
                            ("NYC", "Not Yet Competent"),
                        ],
                        default="NOT_STARTED",
                        help_text="Status of formative (internal) assessments for this module",
                        max_length=15,
                    ),
                ),
                (
                    "formative_completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When formative assessments were completed",
                        null=True,
                    ),
                ),
                (
                    "formative_competent_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of formative assessments marked competent",
                    ),
                ),
                (
                    "formative_total_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total formative assessments for this module",
                    ),
                ),
                (
                    "summative_status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPETENT", "Competent"),
                            ("NYC", "Not Yet Competent"),
                        ],
                        default="NOT_STARTED",
                        help_text="Status of summative (external/EISA) assessments for this module",
                        max_length=15,
                    ),
                ),
                (
                    "summative_completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When summative assessments were completed",
                        null=True,
                    ),
                ),
                (
                    "summative_competent_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of summative assessments marked competent",
                    ),
                ),
                (
                    "summative_total_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total summative assessments for this module",
                    ),
                ),
                (
                    "overall_status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPETENT", "Competent"),
                            ("NYC", "Not Yet Competent"),
                        ],
                        default="NOT_STARTED",
                        help_text="Overall module completion status",
                        max_length=15,
                    ),
                ),
                (
                    "overall_completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When module was fully completed",
                        null=True,
                    ),
                ),
                (
                    "is_manually_overridden",
                    models.BooleanField(
                        default=False,
                        help_text="If True, auto-calculation will be skipped for this record",
                    ),
                ),
                (
                    "override_reason",
                    models.TextField(
                        blank=True, help_text="Reason for manual override"
                    ),
                ),
                (
                    "overridden_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the manual override was applied",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about learner progress"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_progress",
                        to="academics.enrollment",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learner_progress",
                        to="academics.module",
                    ),
                ),
                (
                    "overridden_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who applied the manual override",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="module_progress_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Learner Module Progress",
                "verbose_name_plural": "Learner Module Progress",
                "ordering": [
                    "enrollment",
                    "module__year_level",
                    "module__sequence_order",
                ],
                "unique_together": {("enrollment", "module")},
            },
        ),
    ]
