# Generated by Django 5.2.8 on 2026-01-03 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_qcto_sync_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QCTOAssessmentCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "criteria_code",
                    models.CharField(
                        help_text="e.g., AC1.1, AC1.2 - Assessment Criteria identifier",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Full criteria description from QCTO"),
                ),
                (
                    "is_critical",
                    models.BooleanField(
                        default=False,
                        help_text="Critical criteria must be assessed for competence",
                    ),
                ),
                (
                    "manually_added",
                    models.BooleanField(
                        default=False,
                        help_text="Manually added by SME vs scraped from QCTO",
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qcto_criteria",
                        to="academics.module",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="SME who verified this criteria",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_criteria",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "QCTO Assessment Criteria",
                "verbose_name_plural": "QCTO Assessment Criteria",
                "ordering": ["module", "criteria_code"],
                "unique_together": {("module", "criteria_code")},
            },
        ),
    ]
