# Generated by Django Migration - Renames Block Plan to Implementation Plan
# This migration preserves all existing data

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Renames BlockPlanTemplate, BlockPlanPhase, and BlockPlanModuleSlot 
    to ImplementationPlan, ImplementationPhase, and ImplementationModuleSlot.
    
    Data is preserved through Django's RenameModel operation.
    """

    dependencies = [
        ('academics', '0007_blockplantemplate_blockplanphase_blockplanmoduleslot_and_more'),
    ]

    operations = [
        # Step 1: Rename BlockPlanTemplate -> ImplementationPlan
        migrations.RenameModel(
            old_name='BlockPlanTemplate',
            new_name='ImplementationPlan',
        ),
        
        # Step 2: Rename BlockPlanPhase -> ImplementationPhase
        migrations.RenameModel(
            old_name='BlockPlanPhase',
            new_name='ImplementationPhase',
        ),
        
        # Step 3: Rename BlockPlanModuleSlot -> ImplementationModuleSlot
        migrations.RenameModel(
            old_name='BlockPlanModuleSlot',
            new_name='ImplementationModuleSlot',
        ),
        
        # Step 4: Rename the related_name on Qualification FK from 'block_plan_templates' -> 'implementation_plans'
        migrations.AlterField(
            model_name='implementationplan',
            name='qualification',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                related_name='implementation_plans',
                to='academics.qualification',
            ),
        ),
        
        # Step 5: Rename the related_name on ImplementationPhase.template FK from 'phases' to 'phases' (keep same)
        # The FK field itself is still named 'template' - we'll rename it to 'implementation_plan'
        migrations.RenameField(
            model_name='implementationphase',
            old_name='template',
            new_name='implementation_plan',
        ),
        
        # Step 6: Rename the related_name on Module FK from 'block_plan_slots' -> 'implementation_slots'
        migrations.AlterField(
            model_name='implementationmoduleslot',
            name='module',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                related_name='implementation_slots',
                to='academics.module',
            ),
        ),
        
        # Step 7: Rename the related_name on UnitStandard M2M from 'block_plan_slots' -> 'implementation_slots'
        migrations.AlterField(
            model_name='implementationmoduleslot',
            name='linked_outcomes',
            field=models.ManyToManyField(
                blank=True,
                help_text='Unit standards/outcomes covered in this module slot',
                related_name='implementation_slots',
                to='academics.unitstandard',
            ),
        ),
    ]
