# Generated by Django 5.2.8 on 2026-01-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_rename_blockplan_to_implementationplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='implementationmoduleslot',
            options={'ordering': ['phase', 'sequence'], 'verbose_name': 'Implementation Module Slot', 'verbose_name_plural': 'Implementation Module Slots'},
        ),
        migrations.AlterModelOptions(
            name='implementationphase',
            options={'ordering': ['implementation_plan', 'sequence'], 'verbose_name': 'Implementation Phase', 'verbose_name_plural': 'Implementation Phases'},
        ),
        migrations.AlterModelOptions(
            name='implementationplan',
            options={'ordering': ['qualification', '-is_default', 'name'], 'verbose_name': 'Implementation Plan', 'verbose_name_plural': 'Implementation Plans'},
        ),
        migrations.AlterField(
            model_name='implementationmoduleslot',
            name='linked_outcomes',
            field=models.ManyToManyField(blank=True, help_text='Unit standards/outcomes covered in this module slot', related_name='block_plan_slots', to='academics.unitstandard'),
        ),
    ]
