# Generated by Django 5.2.8 on 2026-01-12 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_implementationmoduleslot_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkplaceModuleOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('outcome_code', models.CharField(help_text='SAQA outcome code (e.g., WM1.1, WM1.2)', max_length=50)),
                ('outcome_number', models.PositiveIntegerField(default=1, help_text='Numeric ordering for the outcome')),
                ('title', models.CharField(help_text='Full outcome title from SAQA curriculum', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Detailed description or assessment criteria')),
                ('range_statement', models.TextField(blank=True, help_text='Range statement or conditions from SAQA curriculum')),
                ('assessment_criteria', models.TextField(blank=True, help_text='Assessment criteria for this outcome')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Estimated hours to demonstrate this outcome', max_digits=5, null=True)),
                ('outcome_group', models.CharField(blank=True, help_text="Group name if outcomes are grouped (e.g., 'Communication Skills')", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('saqa_source', models.CharField(blank=True, help_text='Source URL or document for SAQA import', max_length=255)),
                ('imported_at', models.DateTimeField(blank=True, help_text='When this outcome was imported from SAQA', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(help_text='Workplace module this outcome belongs to', limit_choices_to={'module_type': 'W'}, on_delete=django.db.models.deletion.CASCADE, related_name='workplace_outcomes', to='academics.module')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workplace Module Outcome',
                'verbose_name_plural': 'Workplace Module Outcomes',
                'ordering': ['module', 'outcome_number'],
                'unique_together': {('module', 'outcome_code')},
            },
        ),
    ]
