# Generated by Django 5.2.8 on 2026-01-14 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_feature_improvements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text="e.g., 'Standard 8-Week Foundational Knowledge Block'", max_length=200)),
                ('code', models.CharField(help_text="Short code for reference (e.g., 'INST-FND-8W')", max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('block_type', models.CharField(choices=[('INSTITUTIONAL', 'Institutional Training'), ('WORKPLACE', 'Workplace Stint')], default='INSTITUTIONAL', max_length=20)),
                ('duration_weeks', models.PositiveIntegerField(help_text='Standard duration in weeks')),
                ('applicable_qualification_types', models.JSONField(blank=True, default=list, help_text='Qualification types (OC, NC, ND, PQ, SP, LP) this block applies to (empty = all)')),
                ('contact_days_per_week', models.PositiveIntegerField(default=5, help_text='Training days per week')),
                ('hours_per_day', models.PositiveIntegerField(default=6, help_text='Total hours per training day')),
                ('classroom_hours_per_day', models.PositiveIntegerField(default=2, help_text='Classroom/theory hours per day')),
                ('practical_hours_per_day', models.PositiveIntegerField(default=4, help_text='Practical hours per day')),
                ('workplace_hours_per_day', models.PositiveIntegerField(default=8, help_text='Hours per day for workplace blocks')),
                ('workplace_days_per_week', models.PositiveIntegerField(default=5, help_text='Days per week for workplace blocks')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('color', models.CharField(default='blue', help_text='Color for Gantt chart display', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Standard Block',
                'verbose_name_plural': 'Standard Blocks',
                'ordering': ['block_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='implementationphase',
            name='source_block',
            field=models.ForeignKey(blank=True, help_text='Standard block this phase was generated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_phases', to='academics.standardblock'),
        ),
        migrations.CreateModel(
            name='StandardBlockModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sequence', models.PositiveIntegerField(help_text='Order within the block')),
                ('classroom_sessions', models.PositiveIntegerField(default=1, help_text='Number of classroom/theory sessions')),
                ('practical_sessions', models.PositiveIntegerField(default=1, help_text='Number of practical sessions')),
                ('total_days', models.PositiveIntegerField(help_text='Total training days for this module')),
                ('notes', models.TextField(blank=True, help_text='Delivery notes for this module in this block')),
                ('alternatives', models.ManyToManyField(blank=True, help_text='Alternative modules that can substitute for this one', related_name='alternative_for_block_slots', to='academics.module')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='academics.standardblock')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(help_text='Module to include in this block', on_delete=django.db.models.deletion.CASCADE, related_name='standard_block_slots', to='academics.module')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Standard Block Module',
                'verbose_name_plural': 'Standard Block Modules',
                'ordering': ['block', 'sequence'],
                'unique_together': {('block', 'sequence')},
            },
        ),
        migrations.AddField(
            model_name='implementationmoduleslot',
            name='source_block_module',
            field=models.ForeignKey(blank=True, help_text='Standard block module this slot was generated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_slots', to='academics.standardblockmodule'),
        ),
        migrations.CreateModel(
            name='ImplementationPlanBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sequence', models.PositiveIntegerField(help_text='Order of this block in the implementation plan')),
                ('year_level', models.PositiveIntegerField(default=1, help_text='Which year of study (1, 2, or 3)')),
                ('custom_name', models.CharField(blank=True, help_text='Custom name for this block in this plan (overrides standard name)', max_length=200)),
                ('custom_duration_weeks', models.PositiveIntegerField(blank=True, help_text='Custom duration (overrides standard block duration)', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('generated_phase', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_plan_block', to='academics.implementationphase')),
                ('implementation_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_blocks', to='academics.implementationplan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('standard_block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_usages', to='academics.standardblock')),
            ],
            options={
                'verbose_name': 'Implementation Plan Block',
                'verbose_name_plural': 'Implementation Plan Blocks',
                'ordering': ['implementation_plan', 'sequence'],
                'unique_together': {('implementation_plan', 'sequence')},
            },
        ),
    ]
