# Generated by Django 5.2.8 on 2026-01-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_standard_blocks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualificationcampusaccreditation',
            options={'ordering': ['qualification', 'campus', '-accredited_until'], 'verbose_name': 'Campus Accreditation', 'verbose_name_plural': 'Campus Accreditations'},
        ),
        migrations.AlterUniqueTogether(
            name='qualificationcampusaccreditation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='qualificationcampusaccreditation',
            name='letter_date',
            field=models.DateField(blank=True, help_text='Date the accreditation letter was issued', null=True),
        ),
        migrations.AddField(
            model_name='qualificationcampusaccreditation',
            name='letter_reference',
            field=models.CharField(blank=True, help_text='Accreditation letter reference number', max_length=100),
        ),
        migrations.AddField(
            model_name='qualificationcampusaccreditation',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded'), ('EXPIRED', 'Expired')], default='ACTIVE', help_text='ACTIVE = current, SUPERSEDED = replaced by newer letter, EXPIRED = past end date', max_length=20),
        ),
        migrations.AlterField(
            model_name='qualificationcampusaccreditation',
            name='accreditation_document',
            field=models.FileField(blank=True, help_text='Accreditation letter document', null=True, upload_to='qualifications/campus_accreditation/%Y/'),
        ),
        migrations.AlterField(
            model_name='qualificationcampusaccreditation',
            name='accredited_from',
            field=models.DateField(help_text='Start date of accreditation for this campus'),
        ),
        migrations.AlterField(
            model_name='qualificationcampusaccreditation',
            name='accredited_until',
            field=models.DateField(help_text='End date of accreditation for this campus'),
        ),
    ]
