# Generated by Django 5.2.8 on 2026-01-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_set_existing_accreditations_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementationphase',
            name='phase_type',
            field=models.CharField(choices=[('INDUCTION', 'Induction'), ('INSTITUTIONAL', 'Institutional'), ('WORKPLACE', 'Workplace'), ('WORKPLACE_STINT', 'Workplace Stint'), ('TRADE_TEST', 'Trade Test'), ('ASSESSMENT', 'Assessment')], max_length=20),
        ),
    ]
