# Generated by Django 5.2.8 on 2026-01-28 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_add_phase_type_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('effective_from', models.DateField(help_text='Date this pricing becomes effective')),
                ('effective_to', models.DateField(blank=True, help_text='Date this pricing expires (null = current)', null=True)),
                ('academic_year', models.PositiveIntegerField(help_text='Academic year (e.g., 2026)')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total all-inclusive price shown to learners', max_digits=12)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, help_text='Internal: Registration fee component', max_digits=10)),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=0, help_text='Internal: Tuition fee component', max_digits=10)),
                ('materials_fee', models.DecimalField(decimal_places=2, default=0, help_text='Internal: Materials fee component', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_history', to='academics.qualification')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Qualification Pricing',
                'verbose_name_plural': 'Qualification Pricing',
                'ordering': ['-academic_year', '-effective_from'],
                'indexes': [models.Index(fields=['qualification', 'academic_year'], name='academics_q_qualifi_699839_idx'), models.Index(fields=['effective_from', 'effective_to'], name='academics_q_effecti_e18a0b_idx')],
            },
        ),
    ]
