# Generated by Django 5.2.8 on 2026-01-28 07:49

from django.db import migrations
from datetime import date


def migrate_yearly_pricing(apps, schema_editor):
    """
    Migrate data from QualificationYearlyPricing (finance) to QualificationPricing (academics).
    Maps: registration_fee + tuition_fee + materials_fee -> total_price
    Sets: effective_from to January 1st of academic_year
    """
    QualificationYearlyPricing = apps.get_model('finance', 'QualificationYearlyPricing')
    QualificationPricing = apps.get_model('academics', 'QualificationPricing')
    
    for yearly in QualificationYearlyPricing.objects.all():
        # Calculate total price from components
        total_price = yearly.registration_fee + yearly.tuition_fee + yearly.materials_fee
        
        # Set effective_from to January 1st of the academic year
        effective_from = date(yearly.academic_year, 1, 1)
        
        # Create new pricing record
        QualificationPricing.objects.get_or_create(
            qualification=yearly.qualification,
            academic_year=yearly.academic_year,
            defaults={
                'effective_from': effective_from,
                'effective_to': None,  # Current pricing
                'total_price': total_price,
                'registration_fee': yearly.registration_fee,
                'tuition_fee': yearly.tuition_fee,
                'materials_fee': yearly.materials_fee,
                'is_active': yearly.is_active,
                'notes': yearly.notes,
            }
        )


def reverse_migration(apps, schema_editor):
    """Reverse migration - clear QualificationPricing table"""
    QualificationPricing = apps.get_model('academics', 'QualificationPricing')
    QualificationPricing.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_qualificationpricing'),
        ('finance', '0008_paymentoption_quote_payment_option_quotetemplate_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_yearly_pricing, reverse_migration),
    ]
