# Generated by Django 5.2.8 on 2026-02-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_migrate_yearly_pricing'),
        ('tenants', '0002_extend_campus_code_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelregistration',
            name='campuses',
            field=models.ManyToManyField(blank=True, help_text='Campuses where this person is allocated to work', related_name='registered_personnel', to='tenants.campus'),
        ),
    ]
